# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/manu/Sviluppo/SpinTool/superboucle/edit_clips_ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(536, 516)
        Dialog.setStyleSheet("background-color: rgb(242, 242, 242);")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 470, 511, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.labelMessage = QtWidgets.QLabel(Dialog)
        self.labelMessage.setGeometry(QtCore.QRect(10, 10, 511, 51))
        self.labelMessage.setStyleSheet("font: bold 11pt \"Noto Sans\";\n"
"background-color: rgb(255, 255, 127);")
        self.labelMessage.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.labelMessage.setWordWrap(True)
        self.labelMessage.setObjectName("labelMessage")
        self.frameVolume = QtWidgets.QFrame(Dialog)
        self.frameVolume.setGeometry(QtCore.QRect(10, 190, 511, 271))
        self.frameVolume.setFrameShape(QtWidgets.QFrame.Box)
        self.frameVolume.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameVolume.setObjectName("frameVolume")
        self.checkBoxEnableVolumeChanges = QtWidgets.QCheckBox(self.frameVolume)
        self.checkBoxEnableVolumeChanges.setGeometry(QtCore.QRect(10, 10, 261, 29))
        self.checkBoxEnableVolumeChanges.setObjectName("checkBoxEnableVolumeChanges")
        self.groupBoxVolume = QtWidgets.QGroupBox(self.frameVolume)
        self.groupBoxVolume.setGeometry(QtCore.QRect(10, 40, 481, 201))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBoxVolume.setFont(font)
        self.groupBoxVolume.setStyleSheet("font: bold 10pt \"Noto Sans\";")
        self.groupBoxVolume.setObjectName("groupBoxVolume")
        self.radioButtonSetVolume = QtWidgets.QRadioButton(self.groupBoxVolume)
        self.radioButtonSetVolume.setGeometry(QtCore.QRect(20, 40, 311, 29))
        self.radioButtonSetVolume.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.radioButtonSetVolume.setChecked(True)
        self.radioButtonSetVolume.setObjectName("radioButtonSetVolume")
        self.radioButtonIncreaseVolume = QtWidgets.QRadioButton(self.groupBoxVolume)
        self.radioButtonIncreaseVolume.setGeometry(QtCore.QRect(20, 80, 311, 29))
        self.radioButtonIncreaseVolume.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.radioButtonIncreaseVolume.setObjectName("radioButtonIncreaseVolume")
        self.radioButtonDecreaseVolume = QtWidgets.QRadioButton(self.groupBoxVolume)
        self.radioButtonDecreaseVolume.setGeometry(QtCore.QRect(20, 120, 311, 29))
        self.radioButtonDecreaseVolume.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.radioButtonDecreaseVolume.setObjectName("radioButtonDecreaseVolume")
        self.frameClipVolume = QtWidgets.QFrame(self.groupBoxVolume)
        self.frameClipVolume.setGeometry(QtCore.QRect(20, 165, 271, 41))
        self.frameClipVolume.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameClipVolume.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameClipVolume.setObjectName("frameClipVolume")
        self.buttonCopyVolumeFromCurrentClip = QtWidgets.QPushButton(self.frameClipVolume)
        self.buttonCopyVolumeFromCurrentClip.setGeometry(QtCore.QRect(212, 0, 51, 31))
        self.buttonCopyVolumeFromCurrentClip.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonCopyVolumeFromCurrentClip.setIcon(icon)
        self.buttonCopyVolumeFromCurrentClip.setIconSize(QtCore.QSize(25, 25))
        self.buttonCopyVolumeFromCurrentClip.setObjectName("buttonCopyVolumeFromCurrentClip")
        self.labelVolumeAmount = QtWidgets.QLabel(self.frameClipVolume)
        self.labelVolumeAmount.setGeometry(QtCore.QRect(10, 4, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelVolumeAmount.setFont(font)
        self.labelVolumeAmount.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.labelVolumeAmount.setObjectName("labelVolumeAmount")
        self.spinBoxVolumeAmount = QtWidgets.QSpinBox(self.frameClipVolume)
        self.spinBoxVolumeAmount.setGeometry(QtCore.QRect(120, 0, 87, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.spinBoxVolumeAmount.setFont(font)
        self.spinBoxVolumeAmount.setMaximum(100)
        self.spinBoxVolumeAmount.setObjectName("spinBoxVolumeAmount")
        self.framePorts = QtWidgets.QFrame(Dialog)
        self.framePorts.setGeometry(QtCore.QRect(10, 70, 291, 111))
        self.framePorts.setFrameShape(QtWidgets.QFrame.Box)
        self.framePorts.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePorts.setObjectName("framePorts")
        self.checkBoxEnableOutPortsChanges = QtWidgets.QCheckBox(self.framePorts)
        self.checkBoxEnableOutPortsChanges.setGeometry(QtCore.QRect(10, 10, 161, 29))
        self.checkBoxEnableOutPortsChanges.setObjectName("checkBoxEnableOutPortsChanges")
        self.groupBoxPorts = QtWidgets.QGroupBox(self.framePorts)
        self.groupBoxPorts.setGeometry(QtCore.QRect(10, 40, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBoxPorts.setFont(font)
        self.groupBoxPorts.setStyleSheet("font: bold 10pt \"Noto Sans\";")
        self.groupBoxPorts.setObjectName("groupBoxPorts")
        self.comboBoxOutputPorts = QtWidgets.QComboBox(self.groupBoxPorts)
        self.comboBoxOutputPorts.setGeometry(QtCore.QRect(18, 30, 201, 31))
        self.comboBoxOutputPorts.setObjectName("comboBoxOutputPorts")
        self.buttonCopyPortFromCurrentClip = QtWidgets.QPushButton(self.groupBoxPorts)
        self.buttonCopyPortFromCurrentClip.setGeometry(QtCore.QRect(220, 30, 51, 31))
        self.buttonCopyPortFromCurrentClip.setText("")
        self.buttonCopyPortFromCurrentClip.setIcon(icon)
        self.buttonCopyPortFromCurrentClip.setIconSize(QtCore.QSize(25, 25))
        self.buttonCopyPortFromCurrentClip.setObjectName("buttonCopyPortFromCurrentClip")
        self.frameMuteGroups = QtWidgets.QFrame(Dialog)
        self.frameMuteGroups.setGeometry(QtCore.QRect(310, 70, 211, 111))
        self.frameMuteGroups.setFrameShape(QtWidgets.QFrame.Box)
        self.frameMuteGroups.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMuteGroups.setObjectName("frameMuteGroups")
        self.checkBoxEnableMutGroupChanges = QtWidgets.QCheckBox(self.frameMuteGroups)
        self.checkBoxEnableMutGroupChanges.setGeometry(QtCore.QRect(10, 10, 191, 29))
        self.checkBoxEnableMutGroupChanges.setObjectName("checkBoxEnableMutGroupChanges")
        self.groupBoxMuteGroup = QtWidgets.QGroupBox(self.frameMuteGroups)
        self.groupBoxMuteGroup.setGeometry(QtCore.QRect(10, 40, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBoxMuteGroup.setFont(font)
        self.groupBoxMuteGroup.setStyleSheet("font: bold 10pt \"Noto Sans\";")
        self.groupBoxMuteGroup.setObjectName("groupBoxMuteGroup")
        self.spinBoxMuteGroups = QtWidgets.QSpinBox(self.groupBoxMuteGroup)
        self.spinBoxMuteGroups.setGeometry(QtCore.QRect(20, 30, 91, 31))
        self.spinBoxMuteGroups.setMaximum(999)
        self.spinBoxMuteGroups.setObjectName("spinBoxMuteGroups")
        self.buttonCopyMuteGroupFromCurrentClip = QtWidgets.QPushButton(self.groupBoxMuteGroup)
        self.buttonCopyMuteGroupFromCurrentClip.setGeometry(QtCore.QRect(120, 30, 51, 31))
        self.buttonCopyMuteGroupFromCurrentClip.setText("")
        self.buttonCopyMuteGroupFromCurrentClip.setIcon(icon)
        self.buttonCopyMuteGroupFromCurrentClip.setIconSize(QtCore.QSize(25, 25))
        self.buttonCopyMuteGroupFromCurrentClip.setObjectName("buttonCopyMuteGroupFromCurrentClip")
        self.checkBoxUnselectClips = QtWidgets.QCheckBox(Dialog)
        self.checkBoxUnselectClips.setGeometry(QtCore.QRect(17, 470, 301, 41))
        self.checkBoxUnselectClips.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.checkBoxUnselectClips.setChecked(True)
        self.checkBoxUnselectClips.setObjectName("checkBoxUnselectClips")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Edit clips"))
        self.labelMessage.setText(_translate("Dialog", "message"))
        self.checkBoxEnableVolumeChanges.setText(_translate("Dialog", "Edit"))
        self.groupBoxVolume.setTitle(_translate("Dialog", "Clips volume"))
        self.radioButtonSetVolume.setText(_translate("Dialog", "set to specified volume amount"))
        self.radioButtonIncreaseVolume.setText(_translate("Dialog", "increase by specified volume amount"))
        self.radioButtonDecreaseVolume.setText(_translate("Dialog", "decrease by specified volume amount"))
        self.buttonCopyVolumeFromCurrentClip.setToolTip(_translate("Dialog", "Get volume from current showing clip"))
        self.labelVolumeAmount.setText(_translate("Dialog", "Volume amount"))
        self.checkBoxEnableOutPortsChanges.setText(_translate("Dialog", "Edit"))
        self.groupBoxPorts.setTitle(_translate("Dialog", "Clips port"))
        self.buttonCopyPortFromCurrentClip.setToolTip(_translate("Dialog", "Get port from current showing clip"))
        self.checkBoxEnableMutGroupChanges.setText(_translate("Dialog", "Edit"))
        self.groupBoxMuteGroup.setTitle(_translate("Dialog", "Clips solo group"))
        self.buttonCopyMuteGroupFromCurrentClip.setToolTip(_translate("Dialog", "Get solo group from current showing clip"))
        self.checkBoxUnselectClips.setText(_translate("Dialog", "Unselect clips after processing"))
import gui_rc
