# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/manu/Sviluppo/SpinTool/superboucle/gui_ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(412, 945)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow {background-color: black;}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("#centralwidget {background-color: Black;}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_out = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_out.sizePolicy().hasHeightForWidth())
        self.frame_out.setSizePolicy(sizePolicy)
        self.frame_out.setMinimumSize(QtCore.QSize(236, 890))
        self.frame_out.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_out.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_out.setObjectName("frame_out")
        self.labelLogo = QtWidgets.QLabel(self.frame_out)
        self.labelLogo.setGeometry(QtCore.QRect(0, 0, 231, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLogo.sizePolicy().hasHeightForWidth())
        self.labelLogo.setSizePolicy(sizePolicy)
        self.labelLogo.setText("")
        self.labelLogo.setPixmap(QtGui.QPixmap(":/icons/icons/ST_Logo_XSmall_Transparent.png"))
        self.labelLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLogo.setObjectName("labelLogo")
        self.frame_in = QtWidgets.QFrame(self.frame_out)
        self.frame_in.setGeometry(QtCore.QRect(0, 60, 236, 845))
        self.frame_in.setMinimumSize(QtCore.QSize(236, 845))
        self.frame_in.setStyleSheet("#frame_in {\n"
"background-color: rgb(0, 0, 0);}")
        self.frame_in.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_in.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_in.setObjectName("frame_in")
        self.groupBoxClip = QtWidgets.QGroupBox(self.frame_in)
        self.groupBoxClip.setGeometry(QtCore.QRect(0, 420, 230, 397))
        self.groupBoxClip.setStyleSheet("#groupBoxClip {color: rgb(0, 170, 0);\n"
"background-color: rgb(223, 223, 223);\n"
"font: bold 9pt \"Noto Sans\";\n"
"text-align: left;\n"
"border: 1px solid green;\n"
"border-radius: 5px;}")
        self.groupBoxClip.setObjectName("groupBoxClip")
        self.clip_name = QtWidgets.QLineEdit(self.groupBoxClip)
        self.clip_name.setGeometry(QtCore.QRect(5, 81, 215, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.clip_name.setFont(font)
        self.clip_name.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"border-width: 1px;\n"
"border-color: rgb(250, 250, 250);\n"
"color: rgb(255, 253, 24);\n"
"text-align: center;")
        self.clip_name.setAlignment(QtCore.Qt.AlignCenter)
        self.clip_name.setObjectName("clip_name")
        self.clip_description = QtWidgets.QLabel(self.groupBoxClip)
        self.clip_description.setGeometry(QtCore.QRect(5, 113, 215, 91))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.clip_description.setFont(font)
        self.clip_description.setToolTip("")
        self.clip_description.setToolTipDuration(5)
        self.clip_description.setStatusTip("")
        self.clip_description.setStyleSheet("color: rgb(250, 250, 250);\n"
"background-color: black;\n"
"border-radius: 5px;\n"
"text-align: left;\n"
"font: 10pt \"Noto Sans\";")
        self.clip_description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.clip_description.setWordWrap(True)
        self.clip_description.setObjectName("clip_description")
        self.tabClip = QtWidgets.QTabWidget(self.groupBoxClip)
        self.tabClip.setGeometry(QtCore.QRect(5, 210, 215, 181))
        self.tabClip.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabClip.setAutoFillBackground(False)
        self.tabClip.setStyleSheet("#tabClip {\n"
"font: 8pt \"Noto Sans\";\n"
"background-color: rgb(223, 223, 223);\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid black;\n"
"border-radius: 2px;\n"
"}")
        self.tabClip.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabClip.setIconSize(QtCore.QSize(20, 20))
        self.tabClip.setUsesScrollButtons(True)
        self.tabClip.setTabBarAutoHide(False)
        self.tabClip.setObjectName("tabClip")
        self.tabMeasures = QtWidgets.QWidget()
        self.tabMeasures.setObjectName("tabMeasures")
        self.groupBoxClipOffset = QtWidgets.QGroupBox(self.tabMeasures)
        self.groupBoxClipOffset.setGeometry(QtCore.QRect(0, 53, 203, 91))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.groupBoxClipOffset.setFont(font)
        self.groupBoxClipOffset.setStyleSheet("#groupBoxClipOffset {font: bold 11pt \"Noto Sans\";\n"
"text-align: left top;\n"
"border: 1px solid grey;\n"
"border-radius: 5;}")
        self.groupBoxClipOffset.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxClipOffset.setObjectName("groupBoxClipOffset")
        self.frame_offset = QtWidgets.QSpinBox(self.groupBoxClipOffset)
        self.frame_offset.setGeometry(QtCore.QRect(5, 49, 111, 31))
        self.frame_offset.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 12pt \"Noto Sans\";\n"
"text-align: left;")
        self.frame_offset.setMinimum(-4410000)
        self.frame_offset.setMaximum(4410000)
        self.frame_offset.setObjectName("frame_offset")
        self.label_3 = QtWidgets.QLabel(self.groupBoxClipOffset)
        self.label_3.setGeometry(QtCore.QRect(5, 27, 101, 18))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: italic 10pt \"Noto Sans\";\n"
"text-align: left;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBoxClipOffset)
        self.label_4.setGeometry(QtCore.QRect(127, 27, 61, 18))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: italic 10pt \"Noto Sans\";\n"
"text-align: left;")
        self.label_4.setObjectName("label_4")
        self.beat_offset = QtWidgets.QDoubleSpinBox(self.groupBoxClipOffset)
        self.beat_offset.setEnabled(True)
        self.beat_offset.setGeometry(QtCore.QRect(127, 49, 69, 31))
        self.beat_offset.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 12pt \"Noto Sans\";\n"
"text-align: left;")
        self.beat_offset.setMinimum(-99.0)
        self.beat_offset.setMaximum(99.0)
        self.beat_offset.setSingleStep(0.01)
        self.beat_offset.setProperty("value", 0.0)
        self.beat_offset.setObjectName("beat_offset")
        self.beat_diviser = QtWidgets.QSpinBox(self.tabMeasures)
        self.beat_diviser.setGeometry(QtCore.QRect(130, 10, 71, 31))
        self.beat_diviser.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 12pt \"Noto Sans\";\n"
"text-align: left;")
        self.beat_diviser.setMinimum(1)
        self.beat_diviser.setMaximum(999)
        self.beat_diviser.setObjectName("beat_diviser")
        self.labelBeatAmount = QtWidgets.QLabel(self.tabMeasures)
        self.labelBeatAmount.setGeometry(QtCore.QRect(5, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.labelBeatAmount.setFont(font)
        self.labelBeatAmount.setStyleSheet("color: rgb(160, 6, 89);\n"
"text-align: left;\n"
"font: bold 11pt \"Noto Sans\";\n"
"color: rgb(0, 0, 0);")
        self.labelBeatAmount.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelBeatAmount.setObjectName("labelBeatAmount")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/clip-measures.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabClip.addTab(self.tabMeasures, icon1, "")
        self.tabGroups = QtWidgets.QWidget()
        self.tabGroups.setObjectName("tabGroups")
        self.mute_group = QtWidgets.QSpinBox(self.tabGroups)
        self.mute_group.setGeometry(QtCore.QRect(130, 75, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.mute_group.setFont(font)
        self.mute_group.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 12pt \"Noto Sans\";\n"
"text-align: left;")
        self.mute_group.setObjectName("mute_group")
        self.labelSoloClipGroup = QtWidgets.QLabel(self.tabGroups)
        self.labelSoloClipGroup.setGeometry(QtCore.QRect(5, 75, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.labelSoloClipGroup.setFont(font)
        self.labelSoloClipGroup.setAccessibleName("Help_Clip_SoloGroup")
        self.labelSoloClipGroup.setStyleSheet("color: rgb(160, 6, 89);\n"
"text-align: left;\n"
"font: bold 11pt \"Noto Sans\";\n"
"color: rgb(0, 0, 0);")
        self.labelSoloClipGroup.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelSoloClipGroup.setObjectName("labelSoloClipGroup")
        self.labelSoloClipGroup_2 = QtWidgets.QLabel(self.tabGroups)
        self.labelSoloClipGroup_2.setGeometry(QtCore.QRect(5, 7, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.labelSoloClipGroup_2.setFont(font)
        self.labelSoloClipGroup_2.setAccessibleName("Help_Clip_OutputPort")
        self.labelSoloClipGroup_2.setStyleSheet("font: bold 11pt \"Noto Sans\";\n"
"text-align: left;\n"
"color: rgb(0, 85, 255);")
        self.labelSoloClipGroup_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelSoloClipGroup_2.setObjectName("labelSoloClipGroup_2")
        self.output = QtWidgets.QComboBox(self.tabGroups)
        self.output.setGeometry(QtCore.QRect(5, 37, 201, 23))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.output.setFont(font)
        self.output.setStyleSheet("font: 11pt \"Noto Sans\";\n"
"text-align: left;\n"
"color: rgb(0, 85, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.output.setCurrentText("")
        self.output.setObjectName("output")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/clip-groups.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabClip.addTab(self.tabGroups, icon2, "")
        self.tabBehaviour = QtWidgets.QWidget()
        self.tabBehaviour.setObjectName("tabBehaviour")
        self.always_play_clip = QtWidgets.QCheckBox(self.tabBehaviour)
        self.always_play_clip.setGeometry(QtCore.QRect(5, 90, 141, 29))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.always_play_clip.setFont(font)
        self.always_play_clip.setStyleSheet("font: 11pt \"Noto Sans\";\n"
"text-align: left;")
        self.always_play_clip.setObjectName("always_play_clip")
        self.one_shot_clip = QtWidgets.QCheckBox(self.tabBehaviour)
        self.one_shot_clip.setGeometry(QtCore.QRect(5, 10, 161, 29))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.one_shot_clip.setFont(font)
        self.one_shot_clip.setStyleSheet("font: 11pt \"Noto Sans\";\n"
"text-align: left;")
        self.one_shot_clip.setObjectName("one_shot_clip")
        self.lock_record = QtWidgets.QCheckBox(self.tabBehaviour)
        self.lock_record.setGeometry(QtCore.QRect(5, 50, 161, 29))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lock_record.setFont(font)
        self.lock_record.setStyleSheet("font:  11pt \"Noto Sans\";\n"
"text-align: left;")
        self.lock_record.setObjectName("lock_record")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/clip-behaviour.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabClip.addTab(self.tabBehaviour, icon3, "")
        self.tabFunctions = QtWidgets.QWidget()
        self.tabFunctions.setObjectName("tabFunctions")
        self.btnPaste = QtWidgets.QPushButton(self.tabFunctions)
        self.btnPaste.setGeometry(QtCore.QRect(104, 14, 101, 23))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnPaste.setFont(font)
        self.btnPaste.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 10pt \"Noto Sans\";\n"
"text-align: center;\n"
"color: rgb(0, 0, 0);")
        self.btnPaste.setObjectName("btnPaste")
        self.deleteButton = QtWidgets.QPushButton(self.tabFunctions)
        self.deleteButton.setGeometry(QtCore.QRect(104, 87, 101, 23))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.deleteButton.setFont(font)
        self.deleteButton.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 10pt \"Noto Sans\";\n"
"text-align: center;\n"
"color: rgb(0, 0, 0);")
        self.deleteButton.setObjectName("deleteButton")
        self.exportButton = QtWidgets.QPushButton(self.tabFunctions)
        self.exportButton.setGeometry(QtCore.QRect(104, 50, 101, 23))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.exportButton.setFont(font)
        self.exportButton.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 10pt \"Noto Sans\";\n"
"text-align: center;\n"
"color: rgb(0, 0, 0);")
        self.exportButton.setObjectName("exportButton")
        self.revertButton = QtWidgets.QPushButton(self.tabFunctions)
        self.revertButton.setGeometry(QtCore.QRect(4, 50, 91, 23))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.revertButton.setFont(font)
        self.revertButton.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 10pt \"Noto Sans\";\n"
"text-align: center;\n"
"color: rgb(0, 0, 0);")
        self.revertButton.setObjectName("revertButton")
        self.btnCopy = QtWidgets.QPushButton(self.tabFunctions)
        self.btnCopy.setGeometry(QtCore.QRect(4, 14, 91, 23))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnCopy.setFont(font)
        self.btnCopy.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 10pt \"Noto Sans\";\n"
"text-align: center;\n"
"color: rgb(0, 0, 0);")
        self.btnCopy.setObjectName("btnCopy")
        self.normalizeButton = QtWidgets.QPushButton(self.tabFunctions)
        self.normalizeButton.setGeometry(QtCore.QRect(4, 87, 91, 23))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.normalizeButton.setFont(font)
        self.normalizeButton.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 10pt \"Noto Sans\";\n"
"text-align: center;\n"
"color: rgb(0, 0, 0);")
        self.normalizeButton.setObjectName("normalizeButton")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/clip-functions.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabClip.addTab(self.tabFunctions, icon4, "")
        self.groupBoxClipVolume = QtWidgets.QGroupBox(self.groupBoxClip)
        self.groupBoxClipVolume.setGeometry(QtCore.QRect(5, 21, 215, 56))
        self.groupBoxClipVolume.setStyleSheet("#groupBoxClipVolume {\n"
"border: 1px solid rgb(0, 170, 0);\n"
"border-radius: 5px;\n"
"}")
        self.groupBoxClipVolume.setTitle("")
        self.groupBoxClipVolume.setObjectName("groupBoxClipVolume")
        self.labelClipVolume = QtWidgets.QLabel(self.groupBoxClipVolume)
        self.labelClipVolume.setGeometry(QtCore.QRect(80, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.labelClipVolume.setFont(font)
        self.labelClipVolume.setStyleSheet("color: rgb(0, 170, 0);\n"
"font: bold 11pt \"Noto Sans\";\n"
"text-align: left;")
        self.labelClipVolume.setText("")
        self.labelClipVolume.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelClipVolume.setObjectName("labelClipVolume")
        self.clip_volume = QSuperDial(self.groupBoxClipVolume)
        self.clip_volume.setEnabled(True)
        self.clip_volume.setGeometry(QtCore.QRect(154, 3, 50, 50))
        self.clip_volume.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.clip_volume.setMaximum(256)
        self.clip_volume.setSingleStep(1)
        self.clip_volume.setObjectName("clip_volume")
        self.label_6 = QtWidgets.QLabel(self.groupBoxClipVolume)
        self.label_6.setGeometry(QtCore.QRect(5, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(0, 170, 0);\n"
"font: bold 11pt \"Noto Sans\";\n"
"text-align: left;")
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.groupBoxSong = QtWidgets.QGroupBox(self.frame_in)
        self.groupBoxSong.setGeometry(QtCore.QRect(0, 90, 230, 325))
        self.groupBoxSong.setStyleSheet("#groupBoxSong {color: rgb(160, 6, 89);\n"
"background-color: rgb(223, 223, 223);\n"
"font: bold 9pt \"Noto Sans\";\n"
"text-align: left;\n"
"border: 1px solid purple;\n"
"border-radius: 5px;}")
        self.groupBoxSong.setTitle("Song")
        self.groupBoxSong.setFlat(False)
        self.groupBoxSong.setObjectName("groupBoxSong")
        self.label_11 = QtWidgets.QLabel(self.groupBoxSong)
        self.label_11.setGeometry(QtCore.QRect(5, 246, 121, 26))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(160, 6, 89);\n"
"text-align: left;\n"
"font: bold 11pt \"Noto Sans\";\n"
"color: rgb(0, 0, 0);")
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.stopButton = QtWidgets.QPushButton(self.groupBoxSong)
        self.stopButton.setGeometry(QtCore.QRect(79, 145, 30, 30))
        self.stopButton.setStyleSheet("QPushButton {background-color: rgb(250, 250, 250);\n"
"border: 1px solid grey;\n"
"border-radius: 5px;}\n"
"QPushButton:pressed {background-color: rgb(98, 98, 98);\n"
"border: 1px solid black;\n"
"border-radius: 5px;}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon5)
        self.stopButton.setIconSize(QtCore.QSize(24, 24))
        self.stopButton.setObjectName("stopButton")
        self.recordButton = QtWidgets.QPushButton(self.groupBoxSong)
        self.recordButton.setGeometry(QtCore.QRect(153, 145, 30, 30))
        self.recordButton.setStyleSheet("QPushButton {background-color: rgb(250, 250, 250);\n"
"border: 1px solid grey;\n"
"border-radius: 5px;}\n"
"QPushButton:pressed {background-color: rgb(98, 98, 98);\n"
"border: 1px solid black;\n"
"border-radius: 5px;}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/record_24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.recordButton.setIcon(icon6)
        self.recordButton.setIconSize(QtCore.QSize(24, 24))
        self.recordButton.setObjectName("recordButton")
        self.clip_info_combobox = QtWidgets.QComboBox(self.groupBoxSong)
        self.clip_info_combobox.setGeometry(QtCore.QRect(80, 283, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.clip_info_combobox.setFont(font)
        self.clip_info_combobox.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 12pt \"Noto Sans\";\n"
"text-align: right;\n"
"color: rgb(0, 0, 0);")
        self.clip_info_combobox.setObjectName("clip_info_combobox")
        self.clip_info_combobox.addItem("")
        self.label_13 = QtWidgets.QLabel(self.groupBoxSong)
        self.label_13.setGeometry(QtCore.QRect(5, 283, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(160, 6, 89);\n"
"text-align: left;\n"
"font: bold 11pt \"Noto Sans\";\n"
"color: rgb(0, 0, 0);")
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.rewindButton = QtWidgets.QPushButton(self.groupBoxSong)
        self.rewindButton.setGeometry(QtCore.QRect(5, 145, 30, 30))
        self.rewindButton.setStyleSheet("QPushButton {background-color: rgb(250, 250, 250);\n"
"border: 1px solid grey;\n"
"border-radius: 5px;}\n"
"QPushButton:pressed {background-color: rgb(98, 98, 98);\n"
"border: 1px solid black;\n"
"border-radius: 5px;}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/black_rewind_24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rewindButton.setIcon(icon7)
        self.rewindButton.setIconSize(QtCore.QSize(24, 24))
        self.rewindButton.setObjectName("rewindButton")
        self.gotoTarget = QtWidgets.QSpinBox(self.groupBoxSong)
        self.gotoTarget.setGeometry(QtCore.QRect(130, 186, 91, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gotoTarget.sizePolicy().hasHeightForWidth())
        self.gotoTarget.setSizePolicy(sizePolicy)
        self.gotoTarget.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 12pt \"Noto Sans\";\n"
"text-align: left;\n"
"color: rgb(0, 0, 0);")
        self.gotoTarget.setMinimum(1)
        self.gotoTarget.setMaximum(999999999)
        self.gotoTarget.setObjectName("gotoTarget")
        self.label_12 = QtWidgets.QLabel(self.groupBoxSong)
        self.label_12.setGeometry(QtCore.QRect(5, 186, 131, 26))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label_12.setFont(font)
        self.label_12.setAccessibleName("Help_Transport_GoToPosition")
        self.label_12.setStyleSheet("color: rgb(160, 6, 89);\n"
"text-align: left;\n"
"font: bold 11pt \"Noto Sans\";\n"
"color: rgb(0, 0, 0);")
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.pauseButton = QtWidgets.QPushButton(self.groupBoxSong)
        self.pauseButton.setGeometry(QtCore.QRect(116, 145, 30, 30))
        self.pauseButton.setStyleSheet("QPushButton {background-color: rgb(250, 250, 250);\n"
"border: 1px solid grey;\n"
"border-radius: 5px;}\n"
"QPushButton:pressed {background-color: rgb(98, 98, 98);\n"
"border: 1px solid black;\n"
"border-radius: 5px;}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/black_pause_24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pauseButton.setIcon(icon8)
        self.pauseButton.setIconSize(QtCore.QSize(24, 24))
        self.pauseButton.setObjectName("pauseButton")
        self.playButton = QtWidgets.QPushButton(self.groupBoxSong)
        self.playButton.setGeometry(QtCore.QRect(42, 145, 30, 30))
        self.playButton.setStyleSheet("QPushButton {background-color: rgb(250, 250, 250);\n"
"border: 1px solid grey;\n"
"border-radius: 5px;}\n"
"QPushButton:pressed {background-color: rgb(98, 98, 98);\n"
"border: 1px solid black;\n"
"border-radius: 5px;}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/black_play_24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon9)
        self.playButton.setIconSize(QtCore.QSize(24, 24))
        self.playButton.setObjectName("playButton")
        self.bbtLabel = QtWidgets.QLabel(self.groupBoxSong)
        self.bbtLabel.setGeometry(QtCore.QRect(5, 81, 215, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.bbtLabel.setFont(font)
        self.bbtLabel.setStyleSheet("background-color: black;\n"
"color: rgb(0, 255, 0);\n"
"border: 1px;\n"
"border-radius: 5px;\n"
"font: 75 12pt \"Noto Sans\";")
        self.bbtLabel.setText("")
        self.bbtLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.bbtLabel.setObjectName("bbtLabel")
        self.bpm = QtWidgets.QDoubleSpinBox(self.groupBoxSong)
        self.bpm.setGeometry(QtCore.QRect(130, 216, 91, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bpm.sizePolicy().hasHeightForWidth())
        self.bpm.setSizePolicy(sizePolicy)
        self.bpm.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 12pt \"Noto Sans\";\n"
"text-align: left;\n"
"color: rgb(0, 0, 0);")
        self.bpm.setMinimum(1.0)
        self.bpm.setMaximum(260.0)
        self.bpm.setProperty("value", 120.0)
        self.bpm.setObjectName("bpm")
        self.label_10 = QtWidgets.QLabel(self.groupBoxSong)
        self.label_10.setGeometry(QtCore.QRect(5, 216, 38, 26))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(160, 6, 89);\n"
"text-align: left;\n"
"font: bold 11pt \"Noto Sans\";\n"
"color: rgb(0, 0, 0);")
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gotoButton = QtWidgets.QPushButton(self.groupBoxSong)
        self.gotoButton.setGeometry(QtCore.QRect(190, 145, 30, 30))
        self.gotoButton.setStyleSheet("QPushButton {background-color: rgb(250, 250, 250);\n"
"border: 1px solid grey;\n"
"border-radius: 5px;}\n"
"QPushButton:pressed {background-color: rgb(98, 98, 98);\n"
"border: 1px solid black;\n"
"border-radius: 5px;}")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/black_goto_24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gotoButton.setIcon(icon10)
        self.gotoButton.setIconSize(QtCore.QSize(24, 24))
        self.gotoButton.setObjectName("gotoButton")
        self.beat_per_bar = QtWidgets.QSpinBox(self.groupBoxSong)
        self.beat_per_bar.setGeometry(QtCore.QRect(130, 246, 91, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beat_per_bar.sizePolicy().hasHeightForWidth())
        self.beat_per_bar.setSizePolicy(sizePolicy)
        self.beat_per_bar.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"font: 12pt \"Noto Sans\";\n"
"text-align: left;\n"
"color: rgb(0, 0, 0);")
        self.beat_per_bar.setMinimum(1)
        self.beat_per_bar.setProperty("value", 4)
        self.beat_per_bar.setObjectName("beat_per_bar")
        self.groupBoxSongVolume = QtWidgets.QGroupBox(self.groupBoxSong)
        self.groupBoxSongVolume.setGeometry(QtCore.QRect(5, 21, 215, 56))
        self.groupBoxSongVolume.setStyleSheet("#groupBoxSongVolume {\n"
"border: 1px solid rgb(160, 6, 89);\n"
"border-radius: 5px;\n"
"}")
        self.groupBoxSongVolume.setTitle("")
        self.groupBoxSongVolume.setObjectName("groupBoxSongVolume")
        self.song_volume_knob = QSuperDial(self.groupBoxSongVolume)
        self.song_volume_knob.setGeometry(QtCore.QRect(154, 3, 50, 50))
        self.song_volume_knob.setMaximumSize(QtCore.QSize(60, 60))
        self.song_volume_knob.setStyleSheet("background-color: rgb(223, 27, 130);")
        self.song_volume_knob.setMaximum(256)
        self.song_volume_knob.setInvertedAppearance(False)
        self.song_volume_knob.setInvertedControls(False)
        self.song_volume_knob.setObjectName("song_volume_knob")
        self.labelMasterVolume = QtWidgets.QLabel(self.groupBoxSongVolume)
        self.labelMasterVolume.setGeometry(QtCore.QRect(80, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.labelMasterVolume.setFont(font)
        self.labelMasterVolume.setStyleSheet("font: bold 11pt \"Noto Sans\";\n"
"color: rgb(160, 6, 89);\n"
"text-align: left;")
        self.labelMasterVolume.setText("")
        self.labelMasterVolume.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelMasterVolume.setObjectName("labelMasterVolume")
        self.global_volume_label = QtWidgets.QLabel(self.groupBoxSongVolume)
        self.global_volume_label.setGeometry(QtCore.QRect(5, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.global_volume_label.setFont(font)
        self.global_volume_label.setStyleSheet("font: bold 11pt \"Noto Sans\";\n"
"color: rgb(160, 6, 89);\n"
"text-align: left;")
        self.global_volume_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.global_volume_label.setObjectName("global_volume_label")
        self.groupBoxMessages = QtWidgets.QGroupBox(self.frame_in)
        self.groupBoxMessages.setGeometry(QtCore.QRect(0, 4, 230, 81))
        self.groupBoxMessages.setStyleSheet("#groupBoxMessages {color: rgb(160, 160, 160);\n"
"background-color: rgb(223, 223, 223);\n"
"font: bold 9pt \"Noto Sans\";\n"
"text-align: left;\n"
"border: 1px solid grey;\n"
"border-radius: 5px;}")
        self.groupBoxMessages.setFlat(False)
        self.groupBoxMessages.setCheckable(False)
        self.groupBoxMessages.setObjectName("groupBoxMessages")
        self.labelPerformanceInfo = QtWidgets.QLabel(self.groupBoxMessages)
        self.labelPerformanceInfo.setGeometry(QtCore.QRect(5, 22, 215, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelPerformanceInfo.setFont(font)
        self.labelPerformanceInfo.setStyleSheet("#labelPerformanceInfo {background-color: black;\n"
"font: 10pt \"Noto Sans\";\n"
"color: rgb(175, 178, 178);\n"
"border-radius: 5px;}")
        self.labelPerformanceInfo.setText("")
        self.labelPerformanceInfo.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.labelPerformanceInfo.setObjectName("labelPerformanceInfo")
        self.clipping_label = QtWidgets.QLabel(self.groupBoxMessages)
        self.clipping_label.setGeometry(QtCore.QRect(10, 24, 43, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.clipping_label.setFont(font)
        self.clipping_label.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: bold 11pt \"Noto Sans\";\n"
"text-align: center;\n"
"background-color: rgb(0, 0, 0);\n"
"border: 1px solid black;")
        self.clipping_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.clipping_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.clipping_label.setAlignment(QtCore.Qt.AlignCenter)
        self.clipping_label.setObjectName("clipping_label")
        self.labelRecording = QtWidgets.QLabel(self.groupBoxMessages)
        self.labelRecording.setGeometry(QtCore.QRect(58, 24, 105, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.labelRecording.setFont(font)
        self.labelRecording.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: bold 11pt \"Noto Sans\";\n"
"text-align: center;\n"
"background-color: rgb(0, 0, 0);\n"
"border: 1px solid black;")
        self.labelRecording.setObjectName("labelRecording")
        self.labelShift = QtWidgets.QLabel(self.groupBoxMessages)
        self.labelShift.setGeometry(QtCore.QRect(166, 24, 52, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.labelShift.setFont(font)
        self.labelShift.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: bold 11pt \"Noto Sans\";\n"
"text-align: center;\n"
"background-color: rgb(0, 0, 0);\n"
"border: 1px solid black;")
        self.labelShift.setObjectName("labelShift")
        self.groupBoxSong.raise_()
        self.groupBoxClip.raise_()
        self.groupBoxMessages.raise_()
        self.verticalLayout.addWidget(self.frame_out)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout_out = QtWidgets.QGridLayout()
        self.gridLayout_out.setContentsMargins(12, -1, -1, -1)
        self.gridLayout_out.setSpacing(0)
        self.gridLayout_out.setObjectName("gridLayout_out")
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_out.addItem(spacerItem, 0, 2, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_out.addLayout(self.gridLayout, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_out.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_out.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_out.addItem(spacerItem3, 3, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_out.addItem(spacerItem4, 4, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_out)
        self.horizontalLayout.setStretch(1, 9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 412, 31))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuDevice = QtWidgets.QMenu(self.menubar)
        self.menuDevice.setObjectName("menuDevice")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuInfo = QtWidgets.QMenu(self.menubar)
        self.menuInfo.setObjectName("menuInfo")
        self.menuSong = QtWidgets.QMenu(self.menubar)
        self.menuSong.setObjectName("menuSong")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionAdd_Device = QtWidgets.QAction(MainWindow)
        self.actionAdd_Device.setObjectName("actionAdd_Device")
        self.actionFullScreen = QtWidgets.QAction(MainWindow)
        self.actionFullScreen.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionFullScreen.setObjectName("actionFullScreen")
        self.actionManage_Devices = QtWidgets.QAction(MainWindow)
        self.actionManage_Devices.setObjectName("actionManage_Devices")
        self.actionPlaylist_Editor = QtWidgets.QAction(MainWindow)
        self.actionPlaylist_Editor.setObjectName("actionPlaylist_Editor")
        self.actionPort_Manager = QtWidgets.QAction(MainWindow)
        self.actionPort_Manager.setObjectName("actionPort_Manager")
        self.actionScene_Manager = QtWidgets.QAction(MainWindow)
        self.actionScene_Manager.setObjectName("actionScene_Manager")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionLightDownDevice = QtWidgets.QAction(MainWindow)
        self.actionLightDownDevice.setObjectName("actionLightDownDevice")
        self.actionOnline_Wiki = QtWidgets.QAction(MainWindow)
        self.actionOnline_Wiki.setObjectName("actionOnline_Wiki")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.action_SongAnnotation = QtWidgets.QAction(MainWindow)
        self.action_SongAnnotation.setObjectName("action_SongAnnotation")
        self.actionSystemMessages = QtWidgets.QAction(MainWindow)
        self.actionSystemMessages.setObjectName("actionSystemMessages")
        self.actionExportAllSamples = QtWidgets.QAction(MainWindow)
        self.actionExportAllSamples.setObjectName("actionExportAllSamples")
        self.actionEditSelectedClips = QtWidgets.QAction(MainWindow)
        self.actionEditSelectedClips.setObjectName("actionEditSelectedClips")
        self.actionEditClipsOutputGroup = QtWidgets.QAction(MainWindow)
        self.actionEditClipsOutputGroup.setObjectName("actionEditClipsOutputGroup")
        self.actionEditClipsMuteGroup = QtWidgets.QAction(MainWindow)
        self.actionEditClipsMuteGroup.setObjectName("actionEditClipsMuteGroup")
        self.actionUnselectAllClips = QtWidgets.QAction(MainWindow)
        self.actionUnselectAllClips.setObjectName("actionUnselectAllClips")
        self.actionMixer = QtWidgets.QAction(MainWindow)
        self.actionMixer.setObjectName("actionMixer")
        self.actionStopAllClips = QtWidgets.QAction(MainWindow)
        self.actionStopAllClips.setObjectName("actionStopAllClips")
        self.actionAutoAssignClipsColumn = QtWidgets.QAction(MainWindow)
        self.actionAutoAssignClipsColumn.setObjectName("actionAutoAssignClipsColumn")
        self.actionAutoAssignClipsOutput = QtWidgets.QAction(MainWindow)
        self.actionAutoAssignClipsOutput.setObjectName("actionAutoAssignClipsOutput")
        self.actionAutoAssignClipsSolo = QtWidgets.QAction(MainWindow)
        self.actionAutoAssignClipsSolo.setObjectName("actionAutoAssignClipsSolo")
        self.actionRefresh = QtWidgets.QAction(MainWindow)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionUserManual = QtWidgets.QAction(MainWindow)
        self.actionUserManual.setObjectName("actionUserManual")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionQuit)
        self.menuDevice.addAction(self.actionRefresh)
        self.menuDevice.addSeparator()
        self.menuDevice.addAction(self.actionAdd_Device)
        self.menuDevice.addAction(self.actionManage_Devices)
        self.menuDevice.addSeparator()
        self.menuView.addAction(self.actionFullScreen)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionScene_Manager)
        self.menuView.addAction(self.actionPlaylist_Editor)
        self.menuView.addAction(self.actionPort_Manager)
        self.menuView.addAction(self.actionMixer)
        self.menuView.addAction(self.action_SongAnnotation)
        self.menuView.addAction(self.actionPreferences)
        self.menuInfo.addAction(self.actionOnline_Wiki)
        self.menuInfo.addAction(self.actionUserManual)
        self.menuInfo.addAction(self.actionAbout)
        self.menuSong.addAction(self.actionExportAllSamples)
        self.menuSong.addSeparator()
        self.menuSong.addAction(self.actionEditSelectedClips)
        self.menuSong.addAction(self.actionEditClipsOutputGroup)
        self.menuSong.addAction(self.actionEditClipsMuteGroup)
        self.menuSong.addAction(self.actionUnselectAllClips)
        self.menuSong.addSeparator()
        self.menuSong.addAction(self.actionStopAllClips)
        self.menuSong.addSeparator()
        self.menuSong.addAction(self.actionAutoAssignClipsColumn)
        self.menuSong.addAction(self.actionAutoAssignClipsOutput)
        self.menuSong.addAction(self.actionAutoAssignClipsSolo)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSong.menuAction())
        self.menubar.addAction(self.menuDevice.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())

        self.retranslateUi(MainWindow)
        self.tabClip.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SpinTool"))
        self.groupBoxClip.setTitle(_translate("MainWindow", "Clip"))
        self.clip_description.setText(_translate("MainWindow", "Description"))
        self.groupBoxClipOffset.setAccessibleName(_translate("MainWindow", "Help_Clip_Offset"))
        self.groupBoxClipOffset.setTitle(_translate("MainWindow", "Clip offset"))
        self.frame_offset.setAccessibleName(_translate("MainWindow", "Help_Clip_Offset"))
        self.label_3.setAccessibleName(_translate("MainWindow", "Help_Clip_Offset"))
        self.label_3.setText(_translate("MainWindow", "Sample"))
        self.label_4.setAccessibleName(_translate("MainWindow", "Help_Clip_Offset"))
        self.label_4.setText(_translate("MainWindow", "Beat"))
        self.beat_offset.setAccessibleName(_translate("MainWindow", "Help_Clip_Offset"))
        self.beat_diviser.setAccessibleName(_translate("MainWindow", "Help_Clip_BeatAmount"))
        self.labelBeatAmount.setAccessibleName(_translate("MainWindow", "Help_Clip_BeatAmount"))
        self.labelBeatAmount.setText(_translate("MainWindow", "Beat amount"))
        self.tabClip.setTabToolTip(self.tabClip.indexOf(self.tabMeasures), _translate("MainWindow", "Clip measures (beat amount, offset...)"))
        self.mute_group.setAccessibleName(_translate("MainWindow", "Help_Clip_SoloGroup"))
        self.labelSoloClipGroup.setText(_translate("MainWindow", "Solo clip group"))
        self.labelSoloClipGroup_2.setText(_translate("MainWindow", "Output port"))
        self.output.setAccessibleName(_translate("MainWindow", "Help_Clip_OutputPort"))
        self.tabClip.setTabToolTip(self.tabClip.indexOf(self.tabGroups), _translate("MainWindow", "Clip groups (output port, solo group...)"))
        self.always_play_clip.setToolTip(_translate("MainWindow", "If enabled, clip will always play (also despite of scenes)"))
        self.always_play_clip.setAccessibleName(_translate("MainWindow", "Help_Clip_AlwaysPlay"))
        self.always_play_clip.setText(_translate("MainWindow", "Always play"))
        self.one_shot_clip.setToolTip(_translate("MainWindow", "If enabled, clip will play once (not looping)"))
        self.one_shot_clip.setAccessibleName(_translate("MainWindow", "Help_Clip_OneShot"))
        self.one_shot_clip.setText(_translate("MainWindow", "One-shot"))
        self.lock_record.setToolTip(_translate("MainWindow", "Prevents current clip from recording (play-only)"))
        self.lock_record.setAccessibleName(_translate("MainWindow", "Help_Clip_LockRec"))
        self.lock_record.setText(_translate("MainWindow", "Lock rec"))
        self.tabClip.setTabToolTip(self.tabClip.indexOf(self.tabBehaviour), _translate("MainWindow", "Clip behaviour (one-shot, always play...)"))
        self.btnPaste.setToolTip(_translate("MainWindow", "Gets another clip\'s details from memory and applies them to the current clip"))
        self.btnPaste.setAccessibleName(_translate("MainWindow", "Help_Clip_PasteDetails"))
        self.btnPaste.setText(_translate("MainWindow", "Paste details"))
        self.deleteButton.setToolTip(_translate("MainWindow", "Delete current clip from grid"))
        self.deleteButton.setText(_translate("MainWindow", "Delete Clip"))
        self.exportButton.setToolTip(_translate("MainWindow", "Export current clip sample as audio file"))
        self.exportButton.setText(_translate("MainWindow", "Export Sample"))
        self.revertButton.setToolTip(_translate("MainWindow", "Revert clip sample"))
        self.revertButton.setAccessibleName(_translate("MainWindow", "Help_Clip_Revert"))
        self.revertButton.setText(_translate("MainWindow", "Revert"))
        self.btnCopy.setToolTip(_translate("MainWindow", "Stores current clip\'s details in memory, to apply them to another clip"))
        self.btnCopy.setAccessibleName(_translate("MainWindow", "Help_Clip_CopyDetails"))
        self.btnCopy.setText(_translate("MainWindow", "Copy details"))
        self.normalizeButton.setToolTip(_translate("MainWindow", "Normalize current clip sample"))
        self.normalizeButton.setAccessibleName(_translate("MainWindow", "Help_Clip_Normalize"))
        self.normalizeButton.setText(_translate("MainWindow", "Normalize"))
        self.tabClip.setTabToolTip(self.tabClip.indexOf(self.tabFunctions), _translate("MainWindow", "Clip functions (export, normalize...)"))
        self.label_6.setText(_translate("MainWindow", "Volume"))
        self.label_11.setAccessibleName(_translate("MainWindow", "Help_Song_BeatPerBar"))
        self.label_11.setText(_translate("MainWindow", "Beat per bar"))
        self.stopButton.setToolTip(_translate("MainWindow", "Stop"))
        self.stopButton.setAccessibleName(_translate("MainWindow", "Help_Transport_Generic"))
        self.recordButton.setToolTip(_translate("MainWindow", "Arm for recording"))
        self.recordButton.setAccessibleName(_translate("MainWindow", "Help_Transport_Rec"))
        self.clip_info_combobox.setAccessibleName(_translate("MainWindow", "Help_Clip_Info"))
        self.clip_info_combobox.setCurrentText(_translate("MainWindow", "Volume"))
        self.clip_info_combobox.setItemText(0, _translate("MainWindow", "Volume"))
        self.label_13.setAccessibleName(_translate("MainWindow", "Help_Clip_Info"))
        self.label_13.setText(_translate("MainWindow", "Clip info"))
        self.rewindButton.setToolTip(_translate("MainWindow", "Rewind"))
        self.rewindButton.setAccessibleName(_translate("MainWindow", "Help_Transport_Generic"))
        self.gotoTarget.setAccessibleName(_translate("MainWindow", "Help_Transport_GoToPosition"))
        self.label_12.setText(_translate("MainWindow", "Go to position"))
        self.pauseButton.setToolTip(_translate("MainWindow", "Pause"))
        self.pauseButton.setAccessibleName(_translate("MainWindow", "Help_Transport_Generic"))
        self.playButton.setToolTip(_translate("MainWindow", "Play"))
        self.playButton.setAccessibleName(_translate("MainWindow", "Help_Transport_Generic"))
        self.bpm.setAccessibleName(_translate("MainWindow", "Help_Song_BPM"))
        self.label_10.setAccessibleName(_translate("MainWindow", "Help_Song_BPM"))
        self.label_10.setText(_translate("MainWindow", "BPM"))
        self.gotoButton.setToolTip(_translate("MainWindow", "Go to the specified bar in JACK execution"))
        self.gotoButton.setAccessibleName(_translate("MainWindow", "Help_Transport_GoToPosition"))
        self.beat_per_bar.setAccessibleName(_translate("MainWindow", "Help_Song_BeatPerBar"))
        self.song_volume_knob.setAccessibleName(_translate("MainWindow", "Help_Song_Volume"))
        self.global_volume_label.setAccessibleName(_translate("MainWindow", "Help_Song_Volume"))
        self.global_volume_label.setText(_translate("MainWindow", "Volume"))
        self.groupBoxMessages.setTitle(_translate("MainWindow", "Info"))
        self.clipping_label.setText(_translate("MainWindow", "CLIP!"))
        self.labelRecording.setText(_translate("MainWindow", "ready to REC"))
        self.labelShift.setText(_translate("MainWindow", "SHIFT"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuDevice.setTitle(_translate("MainWindow", "MIDI"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuInfo.setTitle(_translate("MainWindow", "Info"))
        self.menuSong.setTitle(_translate("MainWindow", "Song"))
        self.actionNew.setText(_translate("MainWindow", "New..."))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.actionSave_As.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionAdd_Device.setText(_translate("MainWindow", "New configuration"))
        self.actionFullScreen.setText(_translate("MainWindow", "FullScreen"))
        self.actionFullScreen.setShortcut(_translate("MainWindow", "F11"))
        self.actionManage_Devices.setText(_translate("MainWindow", "Manage configurations"))
        self.actionManage_Devices.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPlaylist_Editor.setText(_translate("MainWindow", "Playlist"))
        self.actionPlaylist_Editor.setShortcut(_translate("MainWindow", "F6"))
        self.actionPort_Manager.setText(_translate("MainWindow", "Output Ports"))
        self.actionPort_Manager.setShortcut(_translate("MainWindow", "F7"))
        self.actionScene_Manager.setText(_translate("MainWindow", "Scenes"))
        self.actionScene_Manager.setShortcut(_translate("MainWindow", "F5"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionPreferences.setShortcut(_translate("MainWindow", "F12"))
        self.actionLightDownDevice.setText(_translate("MainWindow", "Light down device"))
        self.actionOnline_Wiki.setText(_translate("MainWindow", "Online Wiki"))
        self.actionOnline_Wiki.setShortcut(_translate("MainWindow", "F1"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.action_SongAnnotation.setText(_translate("MainWindow", "Song Annotation"))
        self.action_SongAnnotation.setShortcut(_translate("MainWindow", "F8"))
        self.actionSystemMessages.setText(_translate("MainWindow", "System messages"))
        self.actionSystemMessages.setShortcut(_translate("MainWindow", "F9"))
        self.actionExportAllSamples.setText(_translate("MainWindow", "Export all samples"))
        self.actionEditSelectedClips.setText(_translate("MainWindow", "Edit selected clips"))
        self.actionEditClipsOutputGroup.setText(_translate("MainWindow", "Edit clips by output group"))
        self.actionEditClipsMuteGroup.setText(_translate("MainWindow", "Edit clips by solo clip group"))
        self.actionUnselectAllClips.setText(_translate("MainWindow", "Unselect all clips"))
        self.actionUnselectAllClips.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.actionMixer.setText(_translate("MainWindow", "Mixer"))
        self.actionMixer.setShortcut(_translate("MainWindow", "F10"))
        self.actionStopAllClips.setText(_translate("MainWindow", "Stop all clips"))
        self.actionAutoAssignClipsColumn.setText(_translate("MainWindow", "Auto-assign Output port && Solo Group to all clips"))
        self.actionAutoAssignClipsColumn.setIconText(_translate("MainWindow", "Auto-assign Output port & Solo Group to all clips"))
        self.actionAutoAssignClipsOutput.setText(_translate("MainWindow", "Auto-assign Output port"))
        self.actionAutoAssignClipsSolo.setText(_translate("MainWindow", "Auto-assign Solo Group"))
        self.actionRefresh.setText(_translate("MainWindow", "Refresh MIDI devices"))
        self.actionRefresh.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionUserManual.setText(_translate("MainWindow", "User Manual"))
from superboucle.qsuperdial import QSuperDial
import gui_rc
