# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/manu/Sviluppo/SpinTool/superboucle/learn_ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(770, 568)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(11)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("#add_device_frame {border: 0px; border-radius: 10px; background-color: rgb(217, 217, 217);}")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 461, 41))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.labelMidiConfigName = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.labelMidiConfigName.setFont(font)
        self.labelMidiConfigName.setStyleSheet("font: bold 10pt \"Noto Sans\";")
        self.labelMidiConfigName.setObjectName("labelMidiConfigName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelMidiConfigName)
        self.name = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.name.setStyleSheet("font: bold 10pt \"Noto Sans\";")
        self.name.setObjectName("name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name)
        self.tabMIDI = QtWidgets.QTabWidget(Dialog)
        self.tabMIDI.setGeometry(QtCore.QRect(10, 60, 751, 451))
        self.tabMIDI.setStyleSheet("tabMIDI:{font: 10pt \"Noto Sans\";}")
        self.tabMIDI.setObjectName("tabMIDI")
        self.tabTransport = QtWidgets.QWidget()
        self.tabTransport.setObjectName("tabTransport")
        self.groupBoxTransport = QtWidgets.QGroupBox(self.tabTransport)
        self.groupBoxTransport.setGeometry(QtCore.QRect(10, 10, 731, 171))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBoxTransport.setFont(font)
        self.groupBoxTransport.setStyleSheet("font: bold 10pt \"Noto Sans\";\n"
"border-color: rgb(0, 0, 0);")
        self.groupBoxTransport.setObjectName("groupBoxTransport")
        self.playButton = QtWidgets.QPushButton(self.groupBoxTransport)
        self.playButton.setGeometry(QtCore.QRect(10, 65, 36, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/black_play_24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon1)
        self.playButton.setIconSize(QtCore.QSize(24, 24))
        self.playButton.setObjectName("playButton")
        self.gotoButton = QtWidgets.QPushButton(self.groupBoxTransport)
        self.gotoButton.setGeometry(QtCore.QRect(230, 130, 36, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/black_goto_24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gotoButton.setIcon(icon2)
        self.gotoButton.setIconSize(QtCore.QSize(24, 24))
        self.gotoButton.setObjectName("gotoButton")
        self.rewindButton = QtWidgets.QPushButton(self.groupBoxTransport)
        self.rewindButton.setGeometry(QtCore.QRect(10, 130, 36, 30))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/black_rewind_24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rewindButton.setIcon(icon3)
        self.rewindButton.setIconSize(QtCore.QSize(24, 24))
        self.rewindButton.setObjectName("rewindButton")
        self.pauseButton = QtWidgets.QPushButton(self.groupBoxTransport)
        self.pauseButton.setGeometry(QtCore.QRect(230, 65, 36, 30))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/black_pause_24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pauseButton.setIcon(icon4)
        self.pauseButton.setIconSize(QtCore.QSize(24, 24))
        self.pauseButton.setObjectName("pauseButton")
        self.playLabel = QtWidgets.QLabel(self.groupBoxTransport)
        self.playLabel.setGeometry(QtCore.QRect(50, 65, 171, 30))
        self.playLabel.setText("")
        self.playLabel.setObjectName("playLabel")
        self.rewindLabel = QtWidgets.QLabel(self.groupBoxTransport)
        self.rewindLabel.setGeometry(QtCore.QRect(50, 130, 171, 30))
        self.rewindLabel.setText("")
        self.rewindLabel.setObjectName("rewindLabel")
        self.pauseLabel = QtWidgets.QLabel(self.groupBoxTransport)
        self.pauseLabel.setGeometry(QtCore.QRect(270, 65, 171, 30))
        self.pauseLabel.setText("")
        self.pauseLabel.setObjectName("pauseLabel")
        self.gotoLabel = QtWidgets.QLabel(self.groupBoxTransport)
        self.gotoLabel.setGeometry(QtCore.QRect(270, 130, 171, 30))
        self.gotoLabel.setText("")
        self.gotoLabel.setObjectName("gotoLabel")
        self.recordButton = QtWidgets.QPushButton(self.groupBoxTransport)
        self.recordButton.setGeometry(QtCore.QRect(450, 65, 36, 30))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/record_24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.recordButton.setIcon(icon5)
        self.recordButton.setIconSize(QtCore.QSize(24, 24))
        self.recordButton.setObjectName("recordButton")
        self.recordLabel = QtWidgets.QLabel(self.groupBoxTransport)
        self.recordLabel.setGeometry(QtCore.QRect(490, 65, 171, 30))
        self.recordLabel.setText("")
        self.recordLabel.setObjectName("recordLabel")
        self.stopLabel = QtWidgets.QLabel(self.groupBoxTransport)
        self.stopLabel.setGeometry(QtCore.QRect(490, 130, 171, 30))
        self.stopLabel.setText("")
        self.stopLabel.setObjectName("stopLabel")
        self.stopButton = QtWidgets.QPushButton(self.groupBoxTransport)
        self.stopButton.setGeometry(QtCore.QRect(450, 130, 36, 30))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon6)
        self.stopButton.setIconSize(QtCore.QSize(27, 27))
        self.stopButton.setObjectName("stopButton")
        self.labelDescPlay = QtWidgets.QLabel(self.groupBoxTransport)
        self.labelDescPlay.setGeometry(QtCore.QRect(10, 45, 211, 18))
        self.labelDescPlay.setStyleSheet("font: 9pt \"Noto Sans\";")
        self.labelDescPlay.setObjectName("labelDescPlay")
        self.labelDescPause = QtWidgets.QLabel(self.groupBoxTransport)
        self.labelDescPause.setGeometry(QtCore.QRect(230, 45, 211, 18))
        self.labelDescPause.setStyleSheet("font: 9pt \"Noto Sans\";")
        self.labelDescPause.setObjectName("labelDescPause")
        self.labelDescRecord = QtWidgets.QLabel(self.groupBoxTransport)
        self.labelDescRecord.setGeometry(QtCore.QRect(450, 45, 211, 18))
        self.labelDescRecord.setStyleSheet("font: 9pt \"Noto Sans\";")
        self.labelDescRecord.setObjectName("labelDescRecord")
        self.labelDescRewind = QtWidgets.QLabel(self.groupBoxTransport)
        self.labelDescRewind.setGeometry(QtCore.QRect(10, 110, 211, 18))
        self.labelDescRewind.setStyleSheet("font: 9pt \"Noto Sans\";")
        self.labelDescRewind.setObjectName("labelDescRewind")
        self.labelDescGoTo = QtWidgets.QLabel(self.groupBoxTransport)
        self.labelDescGoTo.setGeometry(QtCore.QRect(230, 110, 211, 18))
        self.labelDescGoTo.setStyleSheet("font: 9pt \"Noto Sans\";")
        self.labelDescGoTo.setObjectName("labelDescGoTo")
        self.labelDescStop = QtWidgets.QLabel(self.groupBoxTransport)
        self.labelDescStop.setGeometry(QtCore.QRect(450, 110, 211, 18))
        self.labelDescStop.setStyleSheet("font: 9pt \"Noto Sans\";")
        self.labelDescStop.setObjectName("labelDescStop")
        self.btnResetTransport = QtWidgets.QPushButton(self.groupBoxTransport)
        self.btnResetTransport.setGeometry(QtCore.QRect(650, 0, 81, 31))
        self.btnResetTransport.setStyleSheet("font: 9pt \"Noto Sans\";")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/edit-delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnResetTransport.setIcon(icon7)
        self.btnResetTransport.setIconSize(QtCore.QSize(20, 20))
        self.btnResetTransport.setObjectName("btnResetTransport")
        self.groupBoxOtherFunctions = QtWidgets.QGroupBox(self.tabTransport)
        self.groupBoxOtherFunctions.setGeometry(QtCore.QRect(10, 220, 731, 181))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBoxOtherFunctions.setFont(font)
        self.groupBoxOtherFunctions.setStyleSheet("font: bold 10pt \"Noto Sans\";\n"
"border-color: rgb(202, 202, 202);")
        self.groupBoxOtherFunctions.setFlat(False)
        self.groupBoxOtherFunctions.setObjectName("groupBoxOtherFunctions")
        self.shiftButton = QtWidgets.QPushButton(self.groupBoxOtherFunctions)
        self.shiftButton.setGeometry(QtCore.QRect(10, 65, 36, 30))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/shift.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shiftButton.setIcon(icon8)
        self.shiftButton.setIconSize(QtCore.QSize(24, 24))
        self.shiftButton.setObjectName("shiftButton")
        self.shiftLabel = QtWidgets.QLabel(self.groupBoxOtherFunctions)
        self.shiftLabel.setGeometry(QtCore.QRect(50, 65, 171, 30))
        self.shiftLabel.setText("")
        self.shiftLabel.setObjectName("shiftLabel")
        self.labelDescShift = QtWidgets.QLabel(self.groupBoxOtherFunctions)
        self.labelDescShift.setGeometry(QtCore.QRect(10, 45, 211, 18))
        self.labelDescShift.setStyleSheet("font: 9pt \"Noto Sans\";")
        self.labelDescShift.setObjectName("labelDescShift")
        self.labelDescUnlinkStripeControls = QtWidgets.QLabel(self.groupBoxOtherFunctions)
        self.labelDescUnlinkStripeControls.setGeometry(QtCore.QRect(10, 110, 171, 18))
        self.labelDescUnlinkStripeControls.setStyleSheet("font: 9pt \"Noto Sans\";")
        self.labelDescUnlinkStripeControls.setObjectName("labelDescUnlinkStripeControls")
        self.unlinkStripeControlsButton = QtWidgets.QPushButton(self.groupBoxOtherFunctions)
        self.unlinkStripeControlsButton.setGeometry(QtCore.QRect(10, 130, 36, 30))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/sliders.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.unlinkStripeControlsButton.setIcon(icon9)
        self.unlinkStripeControlsButton.setIconSize(QtCore.QSize(27, 27))
        self.unlinkStripeControlsButton.setObjectName("unlinkStripeControlsButton")
        self.unlinkStripeControlsLabel = QtWidgets.QLabel(self.groupBoxOtherFunctions)
        self.unlinkStripeControlsLabel.setGeometry(QtCore.QRect(50, 130, 171, 30))
        self.unlinkStripeControlsLabel.setText("")
        self.unlinkStripeControlsLabel.setObjectName("unlinkStripeControlsLabel")
        self.btnResetOtherFunctions = QtWidgets.QPushButton(self.groupBoxOtherFunctions)
        self.btnResetOtherFunctions.setGeometry(QtCore.QRect(650, 0, 81, 31))
        self.btnResetOtherFunctions.setStyleSheet("font: 9pt \"Noto Sans\";")
        self.btnResetOtherFunctions.setIcon(icon7)
        self.btnResetOtherFunctions.setIconSize(QtCore.QSize(20, 20))
        self.btnResetOtherFunctions.setObjectName("btnResetOtherFunctions")
        self.customResetButton = QtWidgets.QPushButton(self.groupBoxOtherFunctions)
        self.customResetButton.setGeometry(QtCore.QRect(230, 60, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.customResetButton.setFont(font)
        self.customResetButton.setIconSize(QtCore.QSize(27, 27))
        self.customResetButton.setObjectName("customResetButton")
        self.customResetLabel = QtWidgets.QLabel(self.groupBoxOtherFunctions)
        self.customResetLabel.setGeometry(QtCore.QRect(350, 60, 181, 30))
        self.customResetLabel.setText("")
        self.customResetLabel.setObjectName("customResetLabel")
        self.labelDescCustomReset = QtWidgets.QLabel(self.groupBoxOtherFunctions)
        self.labelDescCustomReset.setGeometry(QtCore.QRect(230, 40, 171, 18))
        self.labelDescCustomReset.setStyleSheet("font: 9pt \"Noto Sans\";")
        self.labelDescCustomReset.setObjectName("labelDescCustomReset")
        self.line = QtWidgets.QFrame(self.tabTransport)
        self.line.setGeometry(QtCore.QRect(10, 195, 731, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.tabMIDI.addTab(self.tabTransport, "")
        self.tabMixer = QtWidgets.QWidget()
        self.tabMixer.setObjectName("tabMixer")
        self.groupBoxMixerOutputPorts = QtWidgets.QGroupBox(self.tabMixer)
        self.groupBoxMixerOutputPorts.setGeometry(QtCore.QRect(10, 10, 721, 301))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxMixerOutputPorts.sizePolicy().hasHeightForWidth())
        self.groupBoxMixerOutputPorts.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBoxMixerOutputPorts.setFont(font)
        self.groupBoxMixerOutputPorts.setStyleSheet("font: bold 10pt \"Noto Sans\";")
        self.groupBoxMixerOutputPorts.setObjectName("groupBoxMixerOutputPorts")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.groupBoxMixerOutputPorts)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 70, 261, 41))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.learn_ctrls = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.learn_ctrls.sizePolicy().hasHeightForWidth())
        self.learn_ctrls.setSizePolicy(sizePolicy)
        self.learn_ctrls.setMinimumSize(QtCore.QSize(177, 0))
        self.learn_ctrls.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.learn_ctrls.setObjectName("learn_ctrls")
        self.gridLayout_6.addWidget(self.learn_ctrls, 0, 0, 1, 1)
        self.stop1 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.stop1.setMinimumSize(QtCore.QSize(10, 0))
        self.stop1.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.stop1.setObjectName("stop1")
        self.gridLayout_6.addWidget(self.stop1, 0, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBoxMixerOutputPorts)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 120, 81, 52))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.ctrlsHorizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.ctrlsHorizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.ctrlsHorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.ctrlsHorizontalLayout.setObjectName("ctrlsHorizontalLayout")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.groupBoxMixerOutputPorts)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 190, 261, 41))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.stop2 = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        self.stop2.setMinimumSize(QtCore.QSize(10, 0))
        self.stop2.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.stop2.setObjectName("stop2")
        self.gridLayout_7.addWidget(self.stop2, 0, 1, 1, 1)
        self.learn_mute_bts = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.learn_mute_bts.sizePolicy().hasHeightForWidth())
        self.learn_mute_bts.setSizePolicy(sizePolicy)
        self.learn_mute_bts.setMinimumSize(QtCore.QSize(177, 0))
        self.learn_mute_bts.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.learn_mute_bts.setObjectName("learn_mute_bts")
        self.gridLayout_7.addWidget(self.learn_mute_bts, 0, 0, 1, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBoxMixerOutputPorts)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 240, 81, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.btsHorizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.btsHorizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.btsHorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.btsHorizontalLayout.setObjectName("btsHorizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBoxMixerOutputPorts)
        self.label.setGeometry(QtCore.QRect(10, 27, 701, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.label.setObjectName("label")
        self.btnResetVolumes = QtWidgets.QPushButton(self.groupBoxMixerOutputPorts)
        self.btnResetVolumes.setGeometry(QtCore.QRect(280, 73, 71, 31))
        self.btnResetVolumes.setStyleSheet("font: 9pt \"Noto Sans\";")
        self.btnResetVolumes.setIcon(icon7)
        self.btnResetVolumes.setIconSize(QtCore.QSize(20, 20))
        self.btnResetVolumes.setObjectName("btnResetVolumes")
        self.btnResetMute = QtWidgets.QPushButton(self.groupBoxMixerOutputPorts)
        self.btnResetMute.setGeometry(QtCore.QRect(280, 193, 71, 31))
        self.btnResetMute.setStyleSheet("font: 9pt \"Noto Sans\";")
        self.btnResetMute.setIcon(icon7)
        self.btnResetMute.setIconSize(QtCore.QSize(20, 20))
        self.btnResetMute.setObjectName("btnResetMute")
        self.groupBox = QtWidgets.QGroupBox(self.tabMixer)
        self.groupBox.setGeometry(QtCore.QRect(10, 330, 381, 71))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("font: bold 10pt \"Noto Sans\";\n"
"border-color: rgb(202, 202, 202);")
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 351, 33))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.learn_song_volume_ctrl = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.learn_song_volume_ctrl.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.learn_song_volume_ctrl.setObjectName("learn_song_volume_ctrl")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.learn_song_volume_ctrl)
        self.label_song_volume_ctrl = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_song_volume_ctrl.setText("")
        self.label_song_volume_ctrl.setObjectName("label_song_volume_ctrl")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_song_volume_ctrl)
        self.btnResetSongVol = QtWidgets.QPushButton(self.tabMixer)
        self.btnResetSongVol.setGeometry(QtCore.QRect(380, 360, 71, 31))
        self.btnResetSongVol.setStyleSheet("font: 9pt \"Noto Sans\";")
        self.btnResetSongVol.setIcon(icon7)
        self.btnResetSongVol.setIconSize(QtCore.QSize(20, 20))
        self.btnResetSongVol.setObjectName("btnResetSongVol")
        self.line_2 = QtWidgets.QFrame(self.tabMixer)
        self.line_2.setGeometry(QtCore.QRect(10, 310, 721, 31))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.tabMIDI.addTab(self.tabMixer, "")
        self.tabSendsAmount = QtWidgets.QWidget()
        self.tabSendsAmount.setObjectName("tabSendsAmount")
        self.groupBoxMixerSends = QtWidgets.QGroupBox(self.tabSendsAmount)
        self.groupBoxMixerSends.setGeometry(QtCore.QRect(10, 10, 721, 301))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxMixerSends.sizePolicy().hasHeightForWidth())
        self.groupBoxMixerSends.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBoxMixerSends.setFont(font)
        self.groupBoxMixerSends.setStyleSheet("font: bold 10pt \"Noto Sans\";")
        self.groupBoxMixerSends.setObjectName("groupBoxMixerSends")
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.groupBoxMixerSends)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(10, 70, 261, 41))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_9.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.learn_send1_ctrls = QtWidgets.QPushButton(self.gridLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.learn_send1_ctrls.sizePolicy().hasHeightForWidth())
        self.learn_send1_ctrls.setSizePolicy(sizePolicy)
        self.learn_send1_ctrls.setMinimumSize(QtCore.QSize(177, 0))
        self.learn_send1_ctrls.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.learn_send1_ctrls.setObjectName("learn_send1_ctrls")
        self.gridLayout_9.addWidget(self.learn_send1_ctrls, 0, 0, 1, 1)
        self.stop_send1_ctrls = QtWidgets.QPushButton(self.gridLayoutWidget_8)
        self.stop_send1_ctrls.setMinimumSize(QtCore.QSize(10, 0))
        self.stop_send1_ctrls.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.stop_send1_ctrls.setObjectName("stop_send1_ctrls")
        self.gridLayout_9.addWidget(self.stop_send1_ctrls, 0, 1, 1, 1)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBoxMixerSends)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 120, 81, 52))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.send1HorizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.send1HorizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.send1HorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.send1HorizontalLayout.setObjectName("send1HorizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBoxMixerSends)
        self.label_4.setGeometry(QtCore.QRect(10, 27, 701, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.label_4.setObjectName("label_4")
        self.btnReset_send1_ctrls = QtWidgets.QPushButton(self.groupBoxMixerSends)
        self.btnReset_send1_ctrls.setGeometry(QtCore.QRect(280, 73, 71, 31))
        self.btnReset_send1_ctrls.setStyleSheet("font: 9pt \"Noto Sans\";")
        self.btnReset_send1_ctrls.setIcon(icon7)
        self.btnReset_send1_ctrls.setIconSize(QtCore.QSize(20, 20))
        self.btnReset_send1_ctrls.setObjectName("btnReset_send1_ctrls")
        self.btnReset_send2_ctrls = QtWidgets.QPushButton(self.groupBoxMixerSends)
        self.btnReset_send2_ctrls.setGeometry(QtCore.QRect(280, 183, 71, 31))
        self.btnReset_send2_ctrls.setStyleSheet("font: 9pt \"Noto Sans\";")
        self.btnReset_send2_ctrls.setIcon(icon7)
        self.btnReset_send2_ctrls.setIconSize(QtCore.QSize(20, 20))
        self.btnReset_send2_ctrls.setObjectName("btnReset_send2_ctrls")
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.groupBoxMixerSends)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(10, 180, 261, 41))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_10.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.learn_send2_ctrls = QtWidgets.QPushButton(self.gridLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.learn_send2_ctrls.sizePolicy().hasHeightForWidth())
        self.learn_send2_ctrls.setSizePolicy(sizePolicy)
        self.learn_send2_ctrls.setMinimumSize(QtCore.QSize(177, 0))
        self.learn_send2_ctrls.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.learn_send2_ctrls.setObjectName("learn_send2_ctrls")
        self.gridLayout_10.addWidget(self.learn_send2_ctrls, 0, 0, 1, 1)
        self.stop_send2_ctrls = QtWidgets.QPushButton(self.gridLayoutWidget_9)
        self.stop_send2_ctrls.setMinimumSize(QtCore.QSize(10, 0))
        self.stop_send2_ctrls.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.stop_send2_ctrls.setObjectName("stop_send2_ctrls")
        self.gridLayout_10.addWidget(self.stop_send2_ctrls, 0, 1, 1, 1)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.groupBoxMixerSends)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 230, 81, 52))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.send2HorizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.send2HorizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.send2HorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.send2HorizontalLayout.setObjectName("send2HorizontalLayout")
        self.tabMIDI.addTab(self.tabSendsAmount, "")
        self.tabClips = QtWidgets.QWidget()
        self.tabClips.setObjectName("tabClips")
        self.label_8 = QtWidgets.QLabel(self.tabClips)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 149, 18))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("font: bold 10pt \"Noto Sans\";")
        self.label_8.setObjectName("label_8")
        self.stop3 = QtWidgets.QPushButton(self.tabClips)
        self.stop3.setGeometry(QtCore.QRect(300, 30, 59, 31))
        self.stop3.setMinimumSize(QtCore.QSize(10, 0))
        self.stop3.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.stop3.setObjectName("stop3")
        self.firstLine = QtWidgets.QPushButton(self.tabClips)
        self.firstLine.setGeometry(QtCore.QRect(10, 30, 281, 31))
        self.firstLine.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.firstLine.setObjectName("firstLine")
        self.layoutWidget = QtWidgets.QWidget(self.tabClips)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 90, 721, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(1000, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btnResetClips = QtWidgets.QPushButton(self.tabClips)
        self.btnResetClips.setGeometry(QtCore.QRect(370, 30, 71, 31))
        self.btnResetClips.setStyleSheet("font: 9pt \"Noto Sans\";")
        self.btnResetClips.setIcon(icon7)
        self.btnResetClips.setIconSize(QtCore.QSize(20, 20))
        self.btnResetClips.setObjectName("btnResetClips")
        self.tabMIDI.addTab(self.tabClips, "")
        self.tabScenes = QtWidgets.QWidget()
        self.tabScenes.setObjectName("tabScenes")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tabScenes)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 10, 720, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_12.sizePolicy().hasHeightForWidth())
        self.groupBox_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setStyleSheet("font: bold 10pt \"Noto Sans\";")
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_12)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 120, 91, 52))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.scenesHorizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.scenesHorizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.scenesHorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.scenesHorizontalLayout.setObjectName("scenesHorizontalLayout")
        self.gridLayoutWidget_12 = QtWidgets.QWidget(self.groupBox_12)
        self.gridLayoutWidget_12.setGeometry(QtCore.QRect(10, 72, 261, 41))
        self.gridLayoutWidget_12.setObjectName("gridLayoutWidget_12")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.gridLayoutWidget_12)
        self.gridLayout_14.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.learn_scenes = QtWidgets.QPushButton(self.gridLayoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.learn_scenes.sizePolicy().hasHeightForWidth())
        self.learn_scenes.setSizePolicy(sizePolicy)
        self.learn_scenes.setMinimumSize(QtCore.QSize(177, 0))
        self.learn_scenes.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.learn_scenes.setObjectName("learn_scenes")
        self.gridLayout_14.addWidget(self.learn_scenes, 0, 0, 1, 1)
        self.stop4 = QtWidgets.QPushButton(self.gridLayoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop4.sizePolicy().hasHeightForWidth())
        self.stop4.setSizePolicy(sizePolicy)
        self.stop4.setMinimumSize(QtCore.QSize(10, 0))
        self.stop4.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.stop4.setObjectName("stop4")
        self.gridLayout_14.addWidget(self.stop4, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_12)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 701, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.label_3.setObjectName("label_3")
        self.btnResetScenes = QtWidgets.QPushButton(self.groupBox_12)
        self.btnResetScenes.setGeometry(QtCore.QRect(280, 76, 71, 31))
        self.btnResetScenes.setStyleSheet("font: 9pt \"Noto Sans\";")
        self.btnResetScenes.setIcon(icon7)
        self.btnResetScenes.setIconSize(QtCore.QSize(20, 20))
        self.btnResetScenes.setObjectName("btnResetScenes")
        self.tabMIDI.addTab(self.tabScenes, "")
        self.tabColors = QtWidgets.QWidget()
        self.tabColors.setObjectName("tabColors")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabColors)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 100, 161, 70))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("font: bold 10pt \"Noto Sans\";")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 143, 33))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.learn_green = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.learn_green.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.learn_green.setObjectName("learn_green")
        self.gridLayout_2.addWidget(self.learn_green, 0, 2, 1, 1)
        self.green_vel = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.green_vel.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.green_vel.setMaximum(127)
        self.green_vel.setObjectName("green_vel")
        self.gridLayout_2.addWidget(self.green_vel, 0, 1, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tabColors)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 10, 161, 70))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setStyleSheet("font: bold 10pt \"Noto Sans\";")
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_8)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 30, 143, 33))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.black_vel = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.black_vel.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.black_vel.setMaximum(127)
        self.black_vel.setObjectName("black_vel")
        self.gridLayout_5.addWidget(self.black_vel, 0, 0, 1, 1)
        self.learn_black = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.learn_black.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.learn_black.setObjectName("learn_black")
        self.gridLayout_5.addWidget(self.learn_black, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabColors)
        self.groupBox_4.setGeometry(QtCore.QRect(210, 100, 161, 70))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("font: bold 10pt \"Noto Sans\";")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_4)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 30, 143, 33))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.blink_green_vel = QtWidgets.QSpinBox(self.gridLayoutWidget_5)
        self.blink_green_vel.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.blink_green_vel.setMaximum(127)
        self.blink_green_vel.setObjectName("blink_green_vel")
        self.gridLayout_8.addWidget(self.blink_green_vel, 0, 0, 1, 1)
        self.learn_blink_green = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.learn_blink_green.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.learn_blink_green.setObjectName("learn_blink_green")
        self.gridLayout_8.addWidget(self.learn_blink_green, 0, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tabColors)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 190, 161, 70))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("font: bold 10pt \"Noto Sans\";")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_5)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 143, 33))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.red_vel = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.red_vel.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.red_vel.setMaximum(127)
        self.red_vel.setObjectName("red_vel")
        self.gridLayout_3.addWidget(self.red_vel, 0, 0, 1, 1)
        self.learn_red = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.learn_red.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.learn_red.setObjectName("learn_red")
        self.gridLayout_3.addWidget(self.learn_red, 0, 1, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tabColors)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 280, 161, 70))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setStyleSheet("font: bold 10pt \"Noto Sans\";")
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayoutWidget_10 = QtWidgets.QWidget(self.groupBox_10)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(10, 30, 143, 33))
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.amber_vel = QtWidgets.QSpinBox(self.gridLayoutWidget_10)
        self.amber_vel.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.amber_vel.setMaximum(127)
        self.amber_vel.setObjectName("amber_vel")
        self.gridLayout_11.addWidget(self.amber_vel, 0, 0, 1, 1)
        self.learn_amber = QtWidgets.QPushButton(self.gridLayoutWidget_10)
        self.learn_amber.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.learn_amber.setObjectName("learn_amber")
        self.gridLayout_11.addWidget(self.learn_amber, 0, 1, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tabColors)
        self.groupBox_11.setGeometry(QtCore.QRect(210, 280, 161, 70))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setStyleSheet("font: bold 10pt \"Noto Sans\";")
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayoutWidget_11 = QtWidgets.QWidget(self.groupBox_11)
        self.gridLayoutWidget_11.setGeometry(QtCore.QRect(10, 30, 143, 33))
        self.gridLayoutWidget_11.setObjectName("gridLayoutWidget_11")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.gridLayoutWidget_11)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.blink_amber_vel = QtWidgets.QSpinBox(self.gridLayoutWidget_11)
        self.blink_amber_vel.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.blink_amber_vel.setMaximum(127)
        self.blink_amber_vel.setObjectName("blink_amber_vel")
        self.gridLayout_12.addWidget(self.blink_amber_vel, 0, 0, 1, 1)
        self.learn_blink_amber = QtWidgets.QPushButton(self.gridLayoutWidget_11)
        self.learn_blink_amber.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.learn_blink_amber.setObjectName("learn_blink_amber")
        self.gridLayout_12.addWidget(self.learn_blink_amber, 0, 1, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tabColors)
        self.groupBox_6.setGeometry(QtCore.QRect(210, 190, 161, 70))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet("font: bold 10pt \"Noto Sans\";")
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_6)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 143, 33))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.blink_red_vel = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.blink_red_vel.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.blink_red_vel.setMaximum(127)
        self.blink_red_vel.setObjectName("blink_red_vel")
        self.gridLayout_4.addWidget(self.blink_red_vel, 0, 0, 1, 1)
        self.learn_blink_red = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.learn_blink_red.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.learn_blink_red.setObjectName("learn_blink_red")
        self.gridLayout_4.addWidget(self.learn_blink_red, 0, 1, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tabColors)
        self.groupBox_9.setGeometry(QtCore.QRect(210, 10, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setWhatsThis("")
        self.groupBox_9.setStyleSheet("font: bold 10pt \"Noto Sans\";")
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.test_color_checkbox = QtWidgets.QCheckBox(self.groupBox_9)
        self.test_color_checkbox.setObjectName("test_color_checkbox")
        self.horizontalLayout.addWidget(self.test_color_checkbox)
        self.test_color_vel = QtWidgets.QSpinBox(self.groupBox_9)
        self.test_color_vel.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.test_color_vel.setMaximum(127)
        self.test_color_vel.setObjectName("test_color_vel")
        self.horizontalLayout.addWidget(self.test_color_vel)
        self.tabMIDI.addTab(self.tabColors, "")
        self.tabInit = QtWidgets.QWidget()
        self.tabInit.setObjectName("tabInit")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tabInit)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 10, 391, 201))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setStyleSheet("font: bold 10pt \"Noto Sans\";\n"
"border-color: rgb(202, 202, 202);")
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_2 = QtWidgets.QLabel(self.groupBox_7)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 351, 41))
        self.label_2.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.init_command = QtWidgets.QTextEdit(self.groupBox_7)
        self.init_command.setGeometry(QtCore.QRect(10, 80, 351, 71))
        self.init_command.setObjectName("init_command")
        self.sendInitButton = QtWidgets.QPushButton(self.groupBox_7)
        self.sendInitButton.setGeometry(QtCore.QRect(10, 160, 171, 31))
        self.sendInitButton.setObjectName("sendInitButton")
        self.tabMIDI.addTab(self.tabInit, "")
        self.tabNotes = QtWidgets.QWidget()
        self.tabNotes.setObjectName("tabNotes")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.tabNotes)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 731, 381))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayoutNotes = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayoutNotes.setContentsMargins(0, 0, 0, 0)
        self.formLayoutNotes.setObjectName("formLayoutNotes")
        self.labelMidiConfigDescription = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.labelMidiConfigDescription.setFont(font)
        self.labelMidiConfigDescription.setStyleSheet("font: bold 10pt  \"Noto Sans\";")
        self.labelMidiConfigDescription.setObjectName("labelMidiConfigDescription")
        self.formLayoutNotes.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelMidiConfigDescription)
        self.plainTextEditDescription = QtWidgets.QPlainTextEdit(self.formLayoutWidget_3)
        self.plainTextEditDescription.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.plainTextEditDescription.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plainTextEditDescription.setLineWidth(2)
        self.plainTextEditDescription.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.plainTextEditDescription.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.plainTextEditDescription.setObjectName("plainTextEditDescription")
        self.formLayoutNotes.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.plainTextEditDescription)
        self.tabMIDI.addTab(self.tabNotes, "")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(580, 510, 181, 61))
        self.buttonBox.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.labelMessage = QtWidgets.QLabel(Dialog)
        self.labelMessage.setGeometry(QtCore.QRect(500, 10, 251, 31))
        self.labelMessage.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: bold 12pt \"Noto Sans\";")
        self.labelMessage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMessage.setObjectName("labelMessage")
        self.labelTip = QtWidgets.QLabel(Dialog)
        self.labelTip.setGeometry(QtCore.QRect(10, 520, 561, 41))
        self.labelTip.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 11pt \"Noto Sans\";")
        self.labelTip.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelTip.setWordWrap(True)
        self.labelTip.setObjectName("labelTip")

        self.retranslateUi(Dialog)
        self.tabMIDI.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "New Device"))
        self.labelMidiConfigName.setText(_translate("Dialog", "MIDI configuration name"))
        self.groupBoxTransport.setAccessibleName(_translate("Dialog", "Help_Learn_Transport"))
        self.groupBoxTransport.setTitle(_translate("Dialog", "Jack Transport"))
        self.playButton.setToolTip(_translate("Dialog", "Play \n"
" (requires a MIDI NOTE)"))
        self.playButton.setAccessibleName(_translate("Dialog", "Help_Learn_Transport"))
        self.gotoButton.setToolTip(_translate("Dialog", "Go to first beat of a specified bar in Jack Transport \n"
" (requires a MIDI NOTE)"))
        self.gotoButton.setAccessibleName(_translate("Dialog", "Help_Learn_Transport"))
        self.rewindButton.setToolTip(_translate("Dialog", "Rewind Jack transport \n"
" (requires a MIDI NOTE)"))
        self.rewindButton.setAccessibleName(_translate("Dialog", "Help_Learn_Transport"))
        self.pauseButton.setToolTip(_translate("Dialog", "Pause Jack transport \n"
" (requires a MIDI NOTE)"))
        self.pauseButton.setAccessibleName(_translate("Dialog", "Help_Learn_Transport"))
        self.recordButton.setToolTip(_translate("Dialog", "Switch on / off recording mode \n"
" (requires a MIDI NOTE)"))
        self.recordButton.setAccessibleName(_translate("Dialog", "Help_Learn_Transport"))
        self.stopButton.setToolTip(_translate("Dialog", "To Stop playing (and rewind Jack transport) \n"
" (requires a MIDI NOTE)"))
        self.stopButton.setAccessibleName(_translate("Dialog", "Help_Learn_Transport"))
        self.labelDescPlay.setText(_translate("Dialog", "Play"))
        self.labelDescPause.setText(_translate("Dialog", "Pause"))
        self.labelDescRecord.setText(_translate("Dialog", "Record"))
        self.labelDescRewind.setText(_translate("Dialog", "Rewind"))
        self.labelDescGoTo.setText(_translate("Dialog", "Go to position"))
        self.labelDescStop.setText(_translate("Dialog", "Stop (& rewind)"))
        self.btnResetTransport.setText(_translate("Dialog", "Reset"))
        self.groupBoxOtherFunctions.setToolTip(_translate("Dialog", "Unlink MIDI controller from mixer stripes: to move MIDI controls without affecting performance"))
        self.groupBoxOtherFunctions.setAccessibleName(_translate("Dialog", "Help_Learn_OtherFunctions"))
        self.groupBoxOtherFunctions.setTitle(_translate("Dialog", "Other functions"))
        self.shiftButton.setToolTip(_translate("Dialog", "To shift some controls and access alternative behaviour  \n"
" (requires a MIDI NOTE)"))
        self.shiftButton.setAccessibleName(_translate("Dialog", "Help_Learn_OtherFunctions"))
        self.labelDescShift.setText(_translate("Dialog", "Shift"))
        self.labelDescUnlinkStripeControls.setText(_translate("Dialog", "Unlink mixer stripes controls"))
        self.unlinkStripeControlsButton.setToolTip(_translate("Dialog", "Interrupt the connection between MIDI controller and mixer stripes controls \n"
" (requires a MIDI NOTE)"))
        self.unlinkStripeControlsButton.setAccessibleName(_translate("Dialog", "Help_Learn_OtherFunctions"))
        self.btnResetOtherFunctions.setText(_translate("Dialog", "Reset"))
        self.customResetButton.setToolTip(_translate("Dialog", "Mixer custom reset"))
        self.customResetButton.setAccessibleName(_translate("Dialog", "Help_Learn_OtherFunctions"))
        self.customResetButton.setText(_translate("Dialog", "Custom reset"))
        self.labelDescCustomReset.setText(_translate("Dialog", "Mixer custom reset"))
        self.tabMIDI.setTabText(self.tabMIDI.indexOf(self.tabTransport), _translate("Dialog", "Transport && commands"))
        self.groupBoxMixerOutputPorts.setAccessibleName(_translate("Dialog", "Help_Learn_OutputPortsControls"))
        self.groupBoxMixerOutputPorts.setTitle(_translate("Dialog", "Output ports controls"))
        self.learn_ctrls.setToolTip(_translate("Dialog", "(requires some MIDI CONTROLS: sliders or knobs)"))
        self.learn_ctrls.setAccessibleName(_translate("Dialog", "Help_Learn_OutputPortsControls"))
        self.learn_ctrls.setText(_translate("Dialog", "Learn volume controllers"))
        self.stop1.setText(_translate("Dialog", "Stop"))
        self.stop2.setText(_translate("Dialog", "Stop"))
        self.learn_mute_bts.setToolTip(_translate("Dialog", "(requires some MIDI NOTES)"))
        self.learn_mute_bts.setAccessibleName(_translate("Dialog", "Help_Learn_OutputPortsControls"))
        self.learn_mute_bts.setText(_translate("Dialog", "Learn mute buttons"))
        self.label.setText(_translate("Dialog", "(Volume and mute controllers refer to Mixer output ports in the same order as shown in Mixer / Port manager)"))
        self.btnResetVolumes.setText(_translate("Dialog", "Reset"))
        self.btnResetMute.setText(_translate("Dialog", "Reset"))
        self.groupBox.setAccessibleName(_translate("Dialog", "Help_Learn_SongVolume"))
        self.groupBox.setTitle(_translate("Dialog", "Song volume"))
        self.learn_song_volume_ctrl.setToolTip(_translate("Dialog", "(requires a MIDI CONTROL: slider or knob)"))
        self.learn_song_volume_ctrl.setAccessibleName(_translate("Dialog", "Help_Learn_SongVolume"))
        self.learn_song_volume_ctrl.setText(_translate("Dialog", "Song Volume Controller"))
        self.btnResetSongVol.setText(_translate("Dialog", "Reset"))
        self.tabMIDI.setTabText(self.tabMIDI.indexOf(self.tabMixer), _translate("Dialog", "Mixer"))
        self.groupBoxMixerSends.setAccessibleName(_translate("Dialog", "Help_Learn_Send_Controls"))
        self.groupBoxMixerSends.setTitle(_translate("Dialog", "Output ports sends amount"))
        self.learn_send1_ctrls.setToolTip(_translate("Dialog", "(requires some MIDI CONTROLS: sliders or knobs)"))
        self.learn_send1_ctrls.setAccessibleName(_translate("Dialog", "Help_Learn_Send_Controls"))
        self.learn_send1_ctrls.setText(_translate("Dialog", "Learn Sends 1 controllers"))
        self.stop_send1_ctrls.setText(_translate("Dialog", "Stop"))
        self.label_4.setText(_translate("Dialog", "(Sends controllers refer to Mixer output ports in the same order as shown in Mixer / Port manager)"))
        self.btnReset_send1_ctrls.setText(_translate("Dialog", "Reset"))
        self.btnReset_send2_ctrls.setText(_translate("Dialog", "Reset"))
        self.learn_send2_ctrls.setToolTip(_translate("Dialog", "(requires some MIDI CONTROLS: sliders or knobs)"))
        self.learn_send2_ctrls.setAccessibleName(_translate("Dialog", "Help_Learn_Send_Controls"))
        self.learn_send2_ctrls.setText(_translate("Dialog", "Learn Sends 2 controllers"))
        self.stop_send2_ctrls.setText(_translate("Dialog", "Stop"))
        self.tabMIDI.setTabText(self.tabMIDI.indexOf(self.tabSendsAmount), _translate("Dialog", "Sends amount"))
        self.label_8.setAccessibleName(_translate("Dialog", "Help_Learn_StartStopButtons"))
        self.label_8.setText(_translate("Dialog", "Start / Stop Buttons"))
        self.stop3.setText(_translate("Dialog", "Stop"))
        self.firstLine.setToolTip(_translate("Dialog", "(requires some MIDI NOTES)"))
        self.firstLine.setAccessibleName(_translate("Dialog", "Help_Learn_StartStopButtons"))
        self.firstLine.setText(_translate("Dialog", "Learn First line"))
        self.btnResetClips.setText(_translate("Dialog", "Reset"))
        self.tabMIDI.setTabText(self.tabMIDI.indexOf(self.tabClips), _translate("Dialog", "Clips"))
        self.groupBox_12.setAccessibleName(_translate("Dialog", "Help_Learn_Scenes"))
        self.groupBox_12.setTitle(_translate("Dialog", "Scenes"))
        self.learn_scenes.setToolTip(_translate("Dialog", "(requires some MIDI NOTES)"))
        self.learn_scenes.setAccessibleName(_translate("Dialog", "Help_Learn_Scenes"))
        self.learn_scenes.setText(_translate("Dialog", "Learn scenes"))
        self.stop4.setText(_translate("Dialog", "Stop"))
        self.label_3.setText(_translate("Dialog", "TIP: it is possible to access further scenes from MIDI device using Shift MIDI button"))
        self.btnResetScenes.setText(_translate("Dialog", "Reset"))
        self.tabMIDI.setTabText(self.tabMIDI.indexOf(self.tabScenes), _translate("Dialog", "Scenes"))
        self.groupBox_3.setAccessibleName(_translate("Dialog", "Help_Learn_Colors"))
        self.groupBox_3.setTitle(_translate("Dialog", "Green Color"))
        self.learn_green.setText(_translate("Dialog", "Test"))
        self.groupBox_8.setAccessibleName(_translate("Dialog", "Help_Learn_Colors"))
        self.groupBox_8.setTitle(_translate("Dialog", "Black Color (light off)"))
        self.learn_black.setText(_translate("Dialog", "Test"))
        self.groupBox_4.setAccessibleName(_translate("Dialog", "Help_Learn_Colors"))
        self.groupBox_4.setTitle(_translate("Dialog", "Blink Green Color"))
        self.learn_blink_green.setText(_translate("Dialog", "Test"))
        self.groupBox_5.setAccessibleName(_translate("Dialog", "Help_Learn_Colors"))
        self.groupBox_5.setTitle(_translate("Dialog", "Red Color"))
        self.learn_red.setText(_translate("Dialog", "Test"))
        self.groupBox_10.setAccessibleName(_translate("Dialog", "Help_Learn_Colors"))
        self.groupBox_10.setTitle(_translate("Dialog", "Amber Color"))
        self.learn_amber.setText(_translate("Dialog", "Test"))
        self.groupBox_11.setAccessibleName(_translate("Dialog", "Help_Learn_Colors"))
        self.groupBox_11.setTitle(_translate("Dialog", "Blink Amber Color"))
        self.learn_blink_amber.setText(_translate("Dialog", "Test"))
        self.groupBox_6.setAccessibleName(_translate("Dialog", "Help_Learn_Colors"))
        self.groupBox_6.setTitle(_translate("Dialog", "Blink Red Color"))
        self.learn_blink_red.setText(_translate("Dialog", "Test"))
        self.groupBox_9.setAccessibleName(_translate("Dialog", "Help_Learn_Colors"))
        self.groupBox_9.setTitle(_translate("Dialog", "Test All Colors"))
        self.test_color_checkbox.setText(_translate("Dialog", "Test"))
        self.tabMIDI.setTabText(self.tabMIDI.indexOf(self.tabColors), _translate("Dialog", "Colors"))
        self.groupBox_7.setAccessibleName(_translate("Dialog", "Help_Learn_Init"))
        self.groupBox_7.setTitle(_translate("Dialog", "Init command (optional)"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p>Init commands as 3 decimal values separated by comma. <br/>One command per line.</p></body></html>"))
        self.sendInitButton.setAccessibleName(_translate("Dialog", "Help_Learn_Init"))
        self.sendInitButton.setText(_translate("Dialog", "Send"))
        self.tabMIDI.setTabText(self.tabMIDI.indexOf(self.tabInit), _translate("Dialog", "Init"))
        self.labelMidiConfigDescription.setText(_translate("Dialog", "Description"))
        self.plainTextEditDescription.setToolTip(_translate("Dialog", "Enter a description for the MIDI configuration"))
        self.plainTextEditDescription.setPlaceholderText(_translate("Dialog", "enter a description for this MIDI configuration"))
        self.tabMIDI.setTabText(self.tabMIDI.indexOf(self.tabNotes), _translate("Dialog", "Notes"))
        self.labelMessage.setText(_translate("Dialog", "message"))
        self.labelTip.setText(_translate("Dialog", "TIP: move over each assignment button to find out supported MIDI element (notes / controls)."))
import gui_rc
