# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/manu/Sviluppo/SpinTool/superboucle/preferences_ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(828, 497)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.tabPreferences = QtWidgets.QTabWidget(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabPreferences.setFont(font)
        self.tabPreferences.setStyleSheet("/* background-color: rgb(242, 242, 242);")
        self.tabPreferences.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabPreferences.setObjectName("tabPreferences")
        self.tabAudioPorts = QtWidgets.QWidget()
        self.tabAudioPorts.setObjectName("tabAudioPorts")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabAudioPorts)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBoxAutoconnect = QtWidgets.QGroupBox(self.tabAudioPorts)
        self.groupBoxAutoconnect.setStyleSheet("font: bold 10pt \"Noto Sans\";")
        self.groupBoxAutoconnect.setObjectName("groupBoxAutoconnect")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBoxAutoconnect)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cBoxAutoconnectOutput = QtWidgets.QCheckBox(self.groupBoxAutoconnect)
        self.cBoxAutoconnectOutput.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cBoxAutoconnectOutput.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.cBoxAutoconnectOutput.setObjectName("cBoxAutoconnectOutput")
        self.verticalLayout_3.addWidget(self.cBoxAutoconnectOutput)
        self.cBoxAutoconnectInput = QtWidgets.QCheckBox(self.groupBoxAutoconnect)
        self.cBoxAutoconnectInput.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cBoxAutoconnectInput.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.cBoxAutoconnectInput.setObjectName("cBoxAutoconnectInput")
        self.verticalLayout_3.addWidget(self.cBoxAutoconnectInput)
        self.verticalLayout_4.addWidget(self.groupBoxAutoconnect)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.tabPreferences.addTab(self.tabAudioPorts, "")
        self.tabEnvironment = QtWidgets.QWidget()
        self.tabEnvironment.setObjectName("tabEnvironment")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabEnvironment)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBoxWinManagement = QtWidgets.QGroupBox(self.tabEnvironment)
        self.groupBoxWinManagement.setAccessibleName("")
        self.groupBoxWinManagement.setStyleSheet("font: bold 10pt \"Noto Sans\";")
        self.groupBoxWinManagement.setObjectName("groupBoxWinManagement")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBoxWinManagement)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cBoxShowPlaylistManager = QtWidgets.QCheckBox(self.groupBoxWinManagement)
        self.cBoxShowPlaylistManager.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cBoxShowPlaylistManager.setAccessibleName("")
        self.cBoxShowPlaylistManager.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.cBoxShowPlaylistManager.setObjectName("cBoxShowPlaylistManager")
        self.verticalLayout.addWidget(self.cBoxShowPlaylistManager)
        self.cBoxShowScenesManager = QtWidgets.QCheckBox(self.groupBoxWinManagement)
        self.cBoxShowScenesManager.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cBoxShowScenesManager.setAccessibleName("")
        self.cBoxShowScenesManager.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.cBoxShowScenesManager.setObjectName("cBoxShowScenesManager")
        self.verticalLayout.addWidget(self.cBoxShowScenesManager)
        self.cBoxShowSongAnnotation = QtWidgets.QCheckBox(self.groupBoxWinManagement)
        self.cBoxShowSongAnnotation.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cBoxShowSongAnnotation.setAccessibleName("")
        self.cBoxShowSongAnnotation.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.cBoxShowSongAnnotation.setObjectName("cBoxShowSongAnnotation")
        self.verticalLayout.addWidget(self.cBoxShowSongAnnotation)
        self.verticalLayout_5.addWidget(self.groupBoxWinManagement)
        self.groupBoxCustomFont = QtWidgets.QGroupBox(self.tabEnvironment)
        self.groupBoxCustomFont.setAccessibleName("")
        self.groupBoxCustomFont.setStyleSheet("font: bold 10pt \"Noto Sans\";")
        self.groupBoxCustomFont.setObjectName("groupBoxCustomFont")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBoxCustomFont)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBoxCustomFont)
        self.label.setAccessibleName("")
        self.label.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.cBigFontSize = QtWidgets.QSpinBox(self.groupBoxCustomFont)
        self.cBigFontSize.setMinimumSize(QtCore.QSize(100, 41))
        self.cBigFontSize.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cBigFontSize.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.cBigFontSize.setMinimum(10)
        self.cBigFontSize.setMaximum(200)
        self.cBigFontSize.setProperty("value", 20)
        self.cBigFontSize.setObjectName("cBigFontSize")
        self.horizontalLayout_2.addWidget(self.cBigFontSize)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.cBoxBigFontScenes = QtWidgets.QCheckBox(self.groupBoxCustomFont)
        self.cBoxBigFontScenes.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cBoxBigFontScenes.setAccessibleName("")
        self.cBoxBigFontScenes.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.cBoxBigFontScenes.setObjectName("cBoxBigFontScenes")
        self.verticalLayout_2.addWidget(self.cBoxBigFontScenes)
        self.cBoxBigFontPlaylist = QtWidgets.QCheckBox(self.groupBoxCustomFont)
        self.cBoxBigFontPlaylist.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cBoxBigFontPlaylist.setAccessibleName("")
        self.cBoxBigFontPlaylist.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.cBoxBigFontPlaylist.setObjectName("cBoxBigFontPlaylist")
        self.verticalLayout_2.addWidget(self.cBoxBigFontPlaylist)
        self.cBoxBigFontPlaylist.raise_()
        self.cBoxBigFontScenes.raise_()
        self.verticalLayout_5.addWidget(self.groupBoxCustomFont)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.tabPreferences.addTab(self.tabEnvironment, "")
        self.tabNewSong = QtWidgets.QWidget()
        self.tabNewSong.setObjectName("tabNewSong")
        self.gridLayout = QtWidgets.QGridLayout(self.tabNewSong)
        self.gridLayout.setObjectName("gridLayout")
        self.labelVG = QtWidgets.QLabel(self.tabNewSong)
        self.labelVG.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.labelVG.setObjectName("labelVG")
        self.gridLayout.addWidget(self.labelVG, 0, 1, 1, 2)
        self.labelDefaultBPM = QtWidgets.QLabel(self.tabNewSong)
        self.labelDefaultBPM.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.labelDefaultBPM.setObjectName("labelDefaultBPM")
        self.gridLayout.addWidget(self.labelDefaultBPM, 3, 0, 1, 1)
        self.spinDefaultBPM = QtWidgets.QSpinBox(self.tabNewSong)
        self.spinDefaultBPM.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.spinDefaultBPM.setMinimum(1)
        self.spinDefaultBPM.setMaximum(260)
        self.spinDefaultBPM.setProperty("value", 120)
        self.spinDefaultBPM.setObjectName("spinDefaultBPM")
        self.gridLayout.addWidget(self.spinDefaultBPM, 3, 1, 1, 1)
        self.labelDefaultSize = QtWidgets.QLabel(self.tabNewSong)
        self.labelDefaultSize.setEnabled(True)
        self.labelDefaultSize.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.labelDefaultSize.setObjectName("labelDefaultSize")
        self.gridLayout.addWidget(self.labelDefaultSize, 1, 0, 1, 1)
        self.spinColumns = QtWidgets.QSpinBox(self.tabNewSong)
        self.spinColumns.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spinColumns.setFont(font)
        self.spinColumns.setFocusPolicy(QtCore.Qt.NoFocus)
        self.spinColumns.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.spinColumns.setMinimum(1)
        self.spinColumns.setMaximum(8)
        self.spinColumns.setProperty("value", 8)
        self.spinColumns.setObjectName("spinColumns")
        self.gridLayout.addWidget(self.spinColumns, 1, 1, 1, 1)
        self.labelDefaultBeats = QtWidgets.QLabel(self.tabNewSong)
        self.labelDefaultBeats.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.labelDefaultBeats.setObjectName("labelDefaultBeats")
        self.gridLayout.addWidget(self.labelDefaultBeats, 4, 0, 1, 1)
        self.spinDefaultBeats = QtWidgets.QSpinBox(self.tabNewSong)
        self.spinDefaultBeats.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.spinDefaultBeats.setMinimum(1)
        self.spinDefaultBeats.setMaximum(99)
        self.spinDefaultBeats.setProperty("value", 4)
        self.spinDefaultBeats.setObjectName("spinDefaultBeats")
        self.gridLayout.addWidget(self.spinDefaultBeats, 4, 1, 1, 1)
        self.spinRows = QtWidgets.QSpinBox(self.tabNewSong)
        self.spinRows.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spinRows.setFont(font)
        self.spinRows.setFocusPolicy(QtCore.Qt.NoFocus)
        self.spinRows.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.spinRows.setMinimum(1)
        self.spinRows.setMaximum(8)
        self.spinRows.setProperty("value", 8)
        self.spinRows.setObjectName("spinRows")
        self.gridLayout.addWidget(self.spinRows, 1, 3, 1, 1)
        self.labelDefaultMasterVolume = QtWidgets.QLabel(self.tabNewSong)
        self.labelDefaultMasterVolume.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.labelDefaultMasterVolume.setObjectName("labelDefaultMasterVolume")
        self.gridLayout.addWidget(self.labelDefaultMasterVolume, 2, 0, 1, 1)
        self.spinDefaultMasterVolume = QtWidgets.QSpinBox(self.tabNewSong)
        self.spinDefaultMasterVolume.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.spinDefaultMasterVolume.setMinimum(0)
        self.spinDefaultMasterVolume.setMaximum(200)
        self.spinDefaultMasterVolume.setProperty("value", 100)
        self.spinDefaultMasterVolume.setObjectName("spinDefaultMasterVolume")
        self.gridLayout.addWidget(self.spinDefaultMasterVolume, 2, 1, 1, 1)
        self.labelHG = QtWidgets.QLabel(self.tabNewSong)
        self.labelHG.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.labelHG.setObjectName("labelHG")
        self.gridLayout.addWidget(self.labelHG, 0, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 5, 1, 1, 1)
        self.tabPreferences.addTab(self.tabNewSong, "")
        self.tabPerformance = QtWidgets.QWidget()
        self.tabPerformance.setObjectName("tabPerformance")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tabPerformance)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.cBoxShowDetailsWhenTriggered = QtWidgets.QCheckBox(self.tabPerformance)
        self.cBoxShowDetailsWhenTriggered.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cBoxShowDetailsWhenTriggered.setAccessibleName("")
        self.cBoxShowDetailsWhenTriggered.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.cBoxShowDetailsWhenTriggered.setObjectName("cBoxShowDetailsWhenTriggered")
        self.verticalLayout_6.addWidget(self.cBoxShowDetailsWhenTriggered)
        self.cBoxPlayAfterRecord = QtWidgets.QCheckBox(self.tabPerformance)
        self.cBoxPlayAfterRecord.setEnabled(True)
        self.cBoxPlayAfterRecord.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cBoxPlayAfterRecord.setAccessibleName("")
        self.cBoxPlayAfterRecord.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.cBoxPlayAfterRecord.setObjectName("cBoxPlayAfterRecord")
        self.verticalLayout_6.addWidget(self.cBoxPlayAfterRecord)
        self.cBoxAllowRecordEmptyClip = QtWidgets.QCheckBox(self.tabPerformance)
        self.cBoxAllowRecordEmptyClip.setEnabled(True)
        self.cBoxAllowRecordEmptyClip.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cBoxAllowRecordEmptyClip.setAccessibleName("")
        self.cBoxAllowRecordEmptyClip.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.cBoxAllowRecordEmptyClip.setObjectName("cBoxAllowRecordEmptyClip")
        self.verticalLayout_6.addWidget(self.cBoxAllowRecordEmptyClip)
        self.groupBoxRecColor = QtWidgets.QGroupBox(self.tabPerformance)
        self.groupBoxRecColor.setAccessibleName("")
        self.groupBoxRecColor.setStyleSheet("font: bold 10pt \"Noto Sans\";")
        self.groupBoxRecColor.setObjectName("groupBoxRecColor")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBoxRecColor)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.rButtonAmberRecColor = QtWidgets.QRadioButton(self.groupBoxRecColor)
        self.rButtonAmberRecColor.setEnabled(True)
        self.rButtonAmberRecColor.setFocusPolicy(QtCore.Qt.NoFocus)
        self.rButtonAmberRecColor.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.rButtonAmberRecColor.setChecked(True)
        self.rButtonAmberRecColor.setObjectName("rButtonAmberRecColor")
        self.verticalLayout_12.addWidget(self.rButtonAmberRecColor)
        self.rButtonRedRecColor = QtWidgets.QRadioButton(self.groupBoxRecColor)
        self.rButtonRedRecColor.setEnabled(True)
        self.rButtonRedRecColor.setFocusPolicy(QtCore.Qt.NoFocus)
        self.rButtonRedRecColor.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.rButtonRedRecColor.setObjectName("rButtonRedRecColor")
        self.verticalLayout_12.addWidget(self.rButtonRedRecColor)
        self.verticalLayout_6.addWidget(self.groupBoxRecColor)
        self.cBoxUnshiftAfterProcessing = QtWidgets.QCheckBox(self.tabPerformance)
        self.cBoxUnshiftAfterProcessing.setEnabled(True)
        self.cBoxUnshiftAfterProcessing.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cBoxUnshiftAfterProcessing.setAccessibleName("")
        self.cBoxUnshiftAfterProcessing.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.cBoxUnshiftAfterProcessing.setObjectName("cBoxUnshiftAfterProcessing")
        self.verticalLayout_6.addWidget(self.cBoxUnshiftAfterProcessing)
        self.cBoxPreventSongSave = QtWidgets.QCheckBox(self.tabPerformance)
        self.cBoxPreventSongSave.setAccessibleName("")
        self.cBoxPreventSongSave.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.cBoxPreventSongSave.setObjectName("cBoxPreventSongSave")
        self.verticalLayout_6.addWidget(self.cBoxPreventSongSave)
        self.cBoxAutoAssignNewClipsColumn = QtWidgets.QCheckBox(self.tabPerformance)
        self.cBoxAutoAssignNewClipsColumn.setAccessibleName("")
        self.cBoxAutoAssignNewClipsColumn.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.cBoxAutoAssignNewClipsColumn.setObjectName("cBoxAutoAssignNewClipsColumn")
        self.verticalLayout_6.addWidget(self.cBoxAutoAssignNewClipsColumn)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.tabPreferences.addTab(self.tabPerformance, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBoxSaveRestoreMixerValues = QtWidgets.QGroupBox(self.tab)
        self.groupBoxSaveRestoreMixerValues.setAccessibleName("")
        self.groupBoxSaveRestoreMixerValues.setStyleSheet("font: bold 10pt \"Noto Sans\";")
        self.groupBoxSaveRestoreMixerValues.setObjectName("groupBoxSaveRestoreMixerValues")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBoxSaveRestoreMixerValues)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cBoxSaveMixerMaster = QtWidgets.QCheckBox(self.groupBoxSaveRestoreMixerValues)
        self.cBoxSaveMixerMaster.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.cBoxSaveMixerMaster.setObjectName("cBoxSaveMixerMaster")
        self.horizontalLayout_5.addWidget(self.cBoxSaveMixerMaster)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cBoxSaveMixerstripGain = QtWidgets.QCheckBox(self.groupBoxSaveRestoreMixerValues)
        self.cBoxSaveMixerstripGain.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.cBoxSaveMixerstripGain.setObjectName("cBoxSaveMixerstripGain")
        self.horizontalLayout_3.addWidget(self.cBoxSaveMixerstripGain)
        self.cBoxSaveMixerstripSend1 = QtWidgets.QCheckBox(self.groupBoxSaveRestoreMixerValues)
        self.cBoxSaveMixerstripSend1.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.cBoxSaveMixerstripSend1.setObjectName("cBoxSaveMixerstripSend1")
        self.horizontalLayout_3.addWidget(self.cBoxSaveMixerstripSend1)
        self.cBoxSaveMixerstripSend2 = QtWidgets.QCheckBox(self.groupBoxSaveRestoreMixerValues)
        self.cBoxSaveMixerstripSend2.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.cBoxSaveMixerstripSend2.setObjectName("cBoxSaveMixerstripSend2")
        self.horizontalLayout_3.addWidget(self.cBoxSaveMixerstripSend2)
        self.cBoxSaveMixerstripVolume = QtWidgets.QCheckBox(self.groupBoxSaveRestoreMixerValues)
        self.cBoxSaveMixerstripVolume.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.cBoxSaveMixerstripVolume.setObjectName("cBoxSaveMixerstripVolume")
        self.horizontalLayout_3.addWidget(self.cBoxSaveMixerstripVolume)
        self.cBoxSaveMixerstripMute = QtWidgets.QCheckBox(self.groupBoxSaveRestoreMixerValues)
        self.cBoxSaveMixerstripMute.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.cBoxSaveMixerstripMute.setObjectName("cBoxSaveMixerstripMute")
        self.horizontalLayout_3.addWidget(self.cBoxSaveMixerstripMute)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.verticalLayout_9.addWidget(self.groupBoxSaveRestoreMixerValues)
        self.groupBoxExcludeFromResetControls = QtWidgets.QGroupBox(self.tab)
        self.groupBoxExcludeFromResetControls.setAccessibleName("")
        self.groupBoxExcludeFromResetControls.setStyleSheet("font: bold 10pt \"Noto Sans\";")
        self.groupBoxExcludeFromResetControls.setObjectName("groupBoxExcludeFromResetControls")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBoxExcludeFromResetControls)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cBoxCustomResetMixerstripGain = QtWidgets.QCheckBox(self.groupBoxExcludeFromResetControls)
        self.cBoxCustomResetMixerstripGain.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.cBoxCustomResetMixerstripGain.setObjectName("cBoxCustomResetMixerstripGain")
        self.horizontalLayout_4.addWidget(self.cBoxCustomResetMixerstripGain)
        self.cBoxCustomResetMixerstripSend1 = QtWidgets.QCheckBox(self.groupBoxExcludeFromResetControls)
        self.cBoxCustomResetMixerstripSend1.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.cBoxCustomResetMixerstripSend1.setObjectName("cBoxCustomResetMixerstripSend1")
        self.horizontalLayout_4.addWidget(self.cBoxCustomResetMixerstripSend1)
        self.cBoxCustomResetMixerstripSend2 = QtWidgets.QCheckBox(self.groupBoxExcludeFromResetControls)
        self.cBoxCustomResetMixerstripSend2.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.cBoxCustomResetMixerstripSend2.setObjectName("cBoxCustomResetMixerstripSend2")
        self.horizontalLayout_4.addWidget(self.cBoxCustomResetMixerstripSend2)
        self.cBoxCustomResetMixerstripVolume = QtWidgets.QCheckBox(self.groupBoxExcludeFromResetControls)
        self.cBoxCustomResetMixerstripVolume.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.cBoxCustomResetMixerstripVolume.setObjectName("cBoxCustomResetMixerstripVolume")
        self.horizontalLayout_4.addWidget(self.cBoxCustomResetMixerstripVolume)
        self.cBoxCustomResetMixerstripMute = QtWidgets.QCheckBox(self.groupBoxExcludeFromResetControls)
        self.cBoxCustomResetMixerstripMute.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.cBoxCustomResetMixerstripMute.setObjectName("cBoxCustomResetMixerstripMute")
        self.horizontalLayout_4.addWidget(self.cBoxCustomResetMixerstripMute)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.verticalLayout_9.addWidget(self.groupBoxExcludeFromResetControls)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem4)
        self.tabPreferences.addTab(self.tab, "")
        self.tabSystem = QtWidgets.QWidget()
        self.tabSystem.setObjectName("tabSystem")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tabSystem)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.cBoxApplySlowerProcessing = QtWidgets.QCheckBox(self.tabSystem)
        self.cBoxApplySlowerProcessing.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cBoxApplySlowerProcessing.setAccessibleName("")
        self.cBoxApplySlowerProcessing.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.cBoxApplySlowerProcessing.setObjectName("cBoxApplySlowerProcessing")
        self.verticalLayout_10.addWidget(self.cBoxApplySlowerProcessing)
        self.cBoxSystemMonitor = QtWidgets.QCheckBox(self.tabSystem)
        self.cBoxSystemMonitor.setStyleSheet("font: 10pt \"Noto Sans\";")
        self.cBoxSystemMonitor.setObjectName("cBoxSystemMonitor")
        self.verticalLayout_10.addWidget(self.cBoxSystemMonitor)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem5)
        self.tabPreferences.addTab(self.tabSystem, "")
        self.verticalLayout_11.addWidget(self.tabPreferences)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelMessage = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelMessage.setFont(font)
        self.labelMessage.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 75 11pt \"Noto Sans\";")
        self.labelMessage.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelMessage.setObjectName("labelMessage")
        self.horizontalLayout.addWidget(self.labelMessage)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.btn_prefs_ok = QtWidgets.QPushButton(Dialog)
        self.btn_prefs_ok.setObjectName("btn_prefs_ok")
        self.horizontalLayout.addWidget(self.btn_prefs_ok)
        self.verticalLayout_11.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.tabPreferences.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Preferences"))
        self.groupBoxAutoconnect.setTitle(_translate("Dialog", "Autoconnect (on application starting)"))
        self.cBoxAutoconnectOutput.setText(_translate("Dialog", "Autoconnect Master output ports to soundcard"))
        self.cBoxAutoconnectInput.setText(_translate("Dialog", "Autoconnect Input ports to soundcard"))
        self.tabPreferences.setTabText(self.tabPreferences.indexOf(self.tabAudioPorts), _translate("Dialog", "Audio ports"))
        self.groupBoxWinManagement.setTitle(_translate("Dialog", "Window management"))
        self.cBoxShowPlaylistManager.setText(_translate("Dialog", "Show playlist window on start up"))
        self.cBoxShowScenesManager.setText(_translate("Dialog", "Show scenes window on start up"))
        self.cBoxShowSongAnnotation.setText(_translate("Dialog", "Show song annotation on song loading"))
        self.groupBoxCustomFont.setTitle(_translate("Dialog", "Custom font size"))
        self.label.setText(_translate("Dialog", "Custom font size (pt)"))
        self.cBoxBigFontScenes.setText(_translate("Dialog", "Use it in scene manager"))
        self.cBoxBigFontPlaylist.setText(_translate("Dialog", "Use it in playlist"))
        self.tabPreferences.setTabText(self.tabPreferences.indexOf(self.tabEnvironment), _translate("Dialog", "Environment"))
        self.labelVG.setText(_translate("Dialog", "Columns (Width)"))
        self.labelDefaultBPM.setText(_translate("Dialog", "Default BPM"))
        self.labelDefaultSize.setText(_translate("Dialog", "Default grid size for new songs"))
        self.labelDefaultBeats.setText(_translate("Dialog", "Default Beats per bar"))
        self.labelDefaultMasterVolume.setText(_translate("Dialog", "Default initial song master volume"))
        self.labelHG.setText(_translate("Dialog", "Lines (Height)"))
        self.tabPreferences.setTabText(self.tabPreferences.indexOf(self.tabNewSong), _translate("Dialog", "New song"))
        self.cBoxShowDetailsWhenTriggered.setText(_translate("Dialog", "Show clip details when triggered on / off"))
        self.cBoxPlayAfterRecord.setText(_translate("Dialog", "Start playing a clip immediately after recording"))
        self.cBoxAllowRecordEmptyClip.setText(_translate("Dialog", "Allow recording on an empy clip from MIDI controller"))
        self.groupBoxRecColor.setTitle(_translate("Dialog", "Cell color for recording clips"))
        self.rButtonAmberRecColor.setText(_translate("Dialog", "AMBER for recording (SuperBoucle default)"))
        self.rButtonRedRecColor.setText(_translate("Dialog", "RED for recording (SpinTool default)"))
        self.cBoxUnshiftAfterProcessing.setText(_translate("Dialog", "Automatically disable Shift function after processing a command"))
        self.cBoxPreventSongSave.setText(_translate("Dialog", "Prevent song save during performance (while Jack is playing)"))
        self.cBoxAutoAssignNewClipsColumn.setText(_translate("Dialog", "Auto-assign Output port && Solo clip Group to new clips"))
        self.tabPreferences.setTabText(self.tabPreferences.indexOf(self.tabPerformance), _translate("Dialog", "Performance"))
        self.groupBoxSaveRestoreMixerValues.setTitle(_translate("Dialog", "Restore / save controls values on application starting / closing"))
        self.cBoxSaveMixerMaster.setText(_translate("Dialog", "Master"))
        self.cBoxSaveMixerstripGain.setText(_translate("Dialog", "Gain"))
        self.cBoxSaveMixerstripSend1.setText(_translate("Dialog", "Send1 amount"))
        self.cBoxSaveMixerstripSend2.setText(_translate("Dialog", "Send2 amount"))
        self.cBoxSaveMixerstripVolume.setText(_translate("Dialog", "Volume"))
        self.cBoxSaveMixerstripMute.setText(_translate("Dialog", "Mute"))
        self.groupBoxExcludeFromResetControls.setTitle(_translate("Dialog", "Exclude from custom reset"))
        self.cBoxCustomResetMixerstripGain.setText(_translate("Dialog", "Gain"))
        self.cBoxCustomResetMixerstripSend1.setText(_translate("Dialog", "Send1 amount"))
        self.cBoxCustomResetMixerstripSend2.setText(_translate("Dialog", "Send2 amount"))
        self.cBoxCustomResetMixerstripVolume.setText(_translate("Dialog", "Volume"))
        self.cBoxCustomResetMixerstripMute.setText(_translate("Dialog", "Mute"))
        self.tabPreferences.setTabText(self.tabPreferences.indexOf(self.tab), _translate("Dialog", "Mixer"))
        self.cBoxApplySlowerProcessing.setText(_translate("Dialog", "Slower processing (try it for XRuns and MIDI controller lighting issues)"))
        self.cBoxSystemMonitor.setText(_translate("Dialog", "Enable system monitor on start up (show CPU load, available memory, etc)"))
        self.tabPreferences.setTabText(self.tabPreferences.indexOf(self.tabSystem), _translate("Dialog", "System"))
        self.labelMessage.setText(_translate("Dialog", "message"))
        self.btn_prefs_ok.setText(_translate("Dialog", "Ok"))
import gui_rc
